/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package br.com.sicoob.capes.corporativo.componentes.listarAnotacoes.dto {
	import flash.net.registerClassAlias;

	registerClassAlias("br.com.sicoob.sisbr.capes.integracao.negocio.dtos.AnotacaoPessoaDTO",
			AnotacaoPessoaDTO);
    public class AnotacaoPessoaDTO extends AnotacaoPessoaDTOBase {
    }
}