/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Mon Oct 01 10:01:03 BRT 2012.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (AnotacaoPessoaDTO.as).
 */

package br.com.sicoob.capes.corporativo.componentes.listarAnotacoes.dto {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.IDateTime;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class AnotacaoPessoaDTOBase implements IExternalizable {

        private var _codigoCategoriaAnotacao:Number;
        private var _codigoOrigemInfo:Number;
        private var _codigoTipoAnotacao:Number;
		private var _dataHoraAnotacao: IDateTime;
		private var _dataHoraOcorrencia: IDateTime;
	    private var _descricaoCategoriaAnotacao:String;
        private var _descricaoOrigemInfo:String;
        private var _descricaoTipoAnotacao:String;
        private var _flexibilidade:Booleano;
        private var _idAnotacao:Number;
        private var _observacao:String;
        private var _quantidade:Number;
        private var _valor:Number;

        public function set codigoCategoriaAnotacao(value:Number):void {
            _codigoCategoriaAnotacao = value;
        }
        public function get codigoCategoriaAnotacao():Number {
            return _codigoCategoriaAnotacao;
        }

        public function set codigoOrigemInfo(value:Number):void {
            _codigoOrigemInfo = value;
        }
        public function get codigoOrigemInfo():Number {
            return _codigoOrigemInfo;
        }

        public function set codigoTipoAnotacao(value:Number):void {
            _codigoTipoAnotacao = value;
        }
        public function get codigoTipoAnotacao():Number {
            return _codigoTipoAnotacao;
        }
        
        public function set dataHoraAnotacao(value:IDateTime):void {
            _dataHoraAnotacao = value;
        }
        public function get dataHoraAnotacao():IDateTime {
            return _dataHoraAnotacao;
        }

        public function set dataHoraOcorrencia(value:IDateTime):void {
            _dataHoraOcorrencia = value;
        }
        public function get dataHoraOcorrencia():IDateTime {
            return _dataHoraOcorrencia;
        }        

        public function set descricaoCategoriaAnotacao(value:String):void {
            _descricaoCategoriaAnotacao = value;
        }
        public function get descricaoCategoriaAnotacao():String {
            return _descricaoCategoriaAnotacao;
        }

        public function set descricaoOrigemInfo(value:String):void {
            _descricaoOrigemInfo = value;
        }
        public function get descricaoOrigemInfo():String {
            return _descricaoOrigemInfo;
        }

        public function set descricaoTipoAnotacao(value:String):void {
            _descricaoTipoAnotacao = value;
        }
        public function get descricaoTipoAnotacao():String {
            return _descricaoTipoAnotacao;
        }

        public function set flexibilidade(value:Booleano):void {
            _flexibilidade = value;
        }
        public function get flexibilidade():Booleano {
            return _flexibilidade;
        }

        public function set idAnotacao(value:Number):void {
            _idAnotacao = value;
        }
        public function get idAnotacao():Number {
            return _idAnotacao;
        }

        public function set observacao(value:String):void {
            _observacao = value;
        }
        public function get observacao():String {
            return _observacao;
        }

        public function set quantidade(value:Number):void {
            _quantidade = value;
        }
        public function get quantidade():Number {
            return _quantidade;
        }

        public function set valor(value:Number):void {
            _valor = value;
        }
        public function get valor():Number {
            return _valor;
        }

        public function readExternal(input:IDataInput):void {
            _codigoCategoriaAnotacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _codigoOrigemInfo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _codigoTipoAnotacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
           	_dataHoraAnotacao = input.readObject() as IDateTime;
           	_dataHoraOcorrencia = input.readObject() as IDateTime;
	        _descricaoCategoriaAnotacao = input.readObject() as String;
	        _descricaoOrigemInfo = input.readObject() as String;
	        _descricaoTipoAnotacao = input.readObject() as String;
            _flexibilidade = SerializacaoObjetos.lerBooleano(input);
            _idAnotacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
	        _observacao = input.readObject() as String;
            _quantidade = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _valor = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_codigoCategoriaAnotacao);
            output.writeObject(_codigoOrigemInfo);
            output.writeObject(_codigoTipoAnotacao);
			output.writeObject(_dataHoraAnotacao);
        	output.writeObject(_dataHoraOcorrencia);            
            output.writeObject(_descricaoCategoriaAnotacao);
            output.writeObject(_descricaoOrigemInfo);
            output.writeObject(_descricaoTipoAnotacao);
        	SerializacaoObjetos.escreverBooleano(_flexibilidade, output);
            output.writeObject(_idAnotacao);
            output.writeObject(_observacao);
            output.writeObject(_quantidade);
            output.writeObject(_valor);
        }
    }
}