/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Thu Jul 14 10:30:33 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (ContaVO.as).
 */

package br.com.sicoob.capes.comum.vo {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class ContaVOBase implements IExternalizable {

        private var _nomeAgencia:String;
        private var _nomeBanco:String;
        private var _numeroAgencia:String;
        private var _numeroBanco:String;
        private var _numeroConta:String;

        public function set nomeAgencia(value:String):void {
            _nomeAgencia = value;
        }
        public function get nomeAgencia():String {
            return _nomeAgencia;
        }

        public function set nomeBanco(value:String):void {
            _nomeBanco = value;
        }
        public function get nomeBanco():String {
            return _nomeBanco;
        }

        public function set numeroAgencia(value:String):void {
            _numeroAgencia = value;
        }
        public function get numeroAgencia():String {
            return _numeroAgencia;
        }

        public function set numeroBanco(value:String):void {
            _numeroBanco = value;
        }
        public function get numeroBanco():String {
            return _numeroBanco;
        }

        public function set numeroConta(value:String):void {
            _numeroConta = value;
        }
        public function get numeroConta():String {
            return _numeroConta;
        }

        public function readExternal(input:IDataInput):void {
	        _nomeAgencia = input.readObject() as String;
	        _nomeBanco = input.readObject() as String;
	        _numeroAgencia = input.readObject() as String;
	        _numeroBanco = input.readObject() as String;
	        _numeroConta = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_nomeAgencia);
            output.writeObject(_nomeBanco);
            output.writeObject(_numeroAgencia);
            output.writeObject(_numeroBanco);
            output.writeObject(_numeroConta);
        }
    }
}