/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Mon Feb 07 10:49:21 GMT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (AutorizacaoVO.as).
 */

package br.com.sicoob.capes.comum.vo {

    import br.com.bancoob.vo.BancoobVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class EncaminharAutorizacaoVOBase extends BancoobVO {

		private var _cooperativaDestino:String;
		private var _cooperativaOrigem:String;
		private var _dataHoraCadastro:String;
		private var _idAutorizacao:Number;
		private var _idInstituicaoOrigem:Number;
		private var _possuiDocumento:String;
		private var _registroControlado:String;
		private var _tipoAutorizacao:String;
		private var _tipoAutorizacaoLabel:String;
		private var _tipoOperacao:String;
		private var _unidadeDestino:Number;
		private var _unidadeOrigem:Number;
		
		public function set cooperativaDestino(value:String):void {
			_cooperativaDestino = value;
		}
		public function get cooperativaDestino():String {
			return _cooperativaDestino;
		}
		public function set cooperativaOrigem(value:String):void {
			_cooperativaOrigem = value;
		}
		public function get cooperativaOrigem():String {
			return _cooperativaOrigem;
		}		
		public function set dataHoraCadastro(value:String):void {
            _dataHoraCadastro = value;
        }
        public function get dataHoraCadastro():String {
            return _dataHoraCadastro;
        }
		public function get idAutorizacao():Number {
			return _idAutorizacao;
		}		
		public function set idAutorizacao(value:Number):void {
			_idAutorizacao = value;
		}
		public function set idInstituicaoOrigem(value:Number):void {
			_idInstituicaoOrigem = value;
		}
		public function get idInstituicaoOrigem():Number {
			return _idInstituicaoOrigem;
		}		
		public function set possuiDocumento(value:String):void {
			_possuiDocumento = value;
		}
		public function get possuiDocumento():String {
			return _possuiDocumento;
		}
		public function set registroControlado(value:String):void {
			_registroControlado = value;
		}
		public function get registroControlado():String {
			return _registroControlado;
		}
		public function set tipoAutorizacao(value:String):void {
			_tipoAutorizacao = value;
		}
		public function get tipoAutorizacao():String {
			return _tipoAutorizacao;
		}
		public function set tipoAutorizacaoLabel(value:String):void {
			_tipoAutorizacaoLabel = value;
		}
		public function get tipoAutorizacaoLabel():String {
			return _tipoAutorizacaoLabel;
		}
        public function set tipoOperacao(value:String):void {
			_tipoOperacao = value;
        }
        public function get tipoOperacao():String {
            return _tipoOperacao;
        }
		public function set unidadeDestino(value:Number):void {
			_unidadeDestino = value;
		}
		public function get unidadeDestino():Number {
			return _unidadeDestino;
		}	
		public function set unidadeOrigem(value:Number):void {
			_unidadeOrigem = value;
		}
		public function get unidadeOrigem():Number {
			return _unidadeOrigem;
		}	
		
		public function readExternal(input:IDataInput):void {
			_cooperativaDestino = input.readObject() as String;
			_cooperativaOrigem = input.readObject() as String;
			_dataHoraCadastro = input.readObject() as String;
			_idAutorizacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_idInstituicaoOrigem = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_possuiDocumento = input.readObject() as String;
			_registroControlado = input.readObject() as String;
			_tipoAutorizacao = input.readObject() as String;
			_tipoAutorizacaoLabel = input.readObject() as String;
			_tipoOperacao = input.readObject() as String;
			_unidadeDestino = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_unidadeOrigem = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

		public function writeExternal(output:IDataOutput):void {
			output.writeObject(_cooperativaDestino);
			output.writeObject(_cooperativaOrigem);
			output.writeObject(_dataHoraCadastro);
			output.writeObject(_idAutorizacao);
			output.writeObject(_idInstituicaoOrigem);
			output.writeObject(_possuiDocumento);
			output.writeObject(_registroControlado);
			output.writeObject(_tipoAutorizacao);
            output.writeObject(_tipoAutorizacaoLabel);
			output.writeObject(_tipoOperacao);
			output.writeObject(_unidadeDestino);
			output.writeObject(_unidadeOrigem);
        }
    }
}