/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Tue Jan 17 11:40:45 BRST 2012.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (FonteRendaProxy.as).
 */
package br.com.sicoob.capes.comum.vo {
	
	import br.com.bancoob.tipos.Booleano;
	import br.com.bancoob.tipos.IDateTime;
	import br.com.bancoob.tipos.SerializacaoObjetos;
	import br.com.sicoob.capes.comum.enums.SituacaoRegistroEnum;
	
	import flash.utils.IDataInput;
	import flash.utils.IDataOutput;
	
	[Bindable]
	public class FonteRendaProxyBase {
		
		private var _bolPossuiAtivo:Boolean;
		private var _bolRendaFixa:Boolean = false;
		private var _bolSimplesNacional:Boolean;		
		private var _codigoSituacaoAprovacao:Number;
		private var _codigoTipoFonteRenda:Number;
		private var _dataHoraInicio:IDateTime;
		private var _dataValidadeRenda:IDateTime;
		private var _descFonteRenda:String;
		private var _descricaoTipoFonteRenda:String;
		private var _idFonteRenda:Number;
		private var _idInstituicaoAtualizacao:Number;
		private var _idPessoa:Number;
		private var _idPessoaEmpregador:Number;
		private var _idRegistroControlado:String;
		private var _idUsuarioAprovacao:String;
		private var _situacaoAprovacao:SituacaoRegistroEnum;
		private var _valorReceitaBrutaMensal:Number;
		
		public function set bolPossuiAtivo(value:Boolean):void {
			_bolPossuiAtivo = value;
		}
		public function get bolPossuiAtivo():Boolean {
			return _bolPossuiAtivo;
		}
		
		public function get bolRendaFixa():Boolean {
			return _bolRendaFixa;
		}
		
		public function set bolRendaFixa(value:Boolean):void {
			_bolRendaFixa = value;
		}
		
		public function get bolSimplesNacional():Boolean {
			return _bolSimplesNacional;
		}
		
		public function set bolSimplesNacional(value:Boolean):void {
			_bolSimplesNacional = value;
		}
		
		public function get codigoSituacaoAprovacao():Number {
			return _codigoSituacaoAprovacao;
		}
		
		public function set codigoSituacaoAprovacao(value:Number):void {
			_codigoSituacaoAprovacao = value;
		}
		
		public function get codigoTipoFonteRenda():Number {
			return _codigoTipoFonteRenda;
		}
		
		public function set codigoTipoFonteRenda(value:Number):void {
			_codigoTipoFonteRenda = value;
		}
		
		public function get dataHoraInicio():IDateTime {
			return _dataHoraInicio;
		}
		
		public function set dataHoraInicio(value:IDateTime):void {
			_dataHoraInicio = value;
		}
		
		public function get dataValidadeRenda():IDateTime {
			return _dataValidadeRenda;
		}
		
		public function set dataValidadeRenda(value:IDateTime):void {
			_dataValidadeRenda = value;
		}
		
		public function get descFonteRenda():String {
			return _descFonteRenda;
		}
		
		public function set descFonteRenda(value:String):void {
			_descFonteRenda = value;
		}
		
		public function get descricaoTipoFonteRenda():String {
			return _descricaoTipoFonteRenda;
		}
		
		public function set descricaoTipoFonteRenda(value:String):void {
			_descricaoTipoFonteRenda = value;
		}
		
		public function get idFonteRenda():Number {
			return _idFonteRenda;
		}
		
		public function set idFonteRenda(value:Number):void {
			_idFonteRenda = value;
		}
		
		public function get idInstituicaoAtualizacao():Number {
			return _idInstituicaoAtualizacao;
		}
		
		public function set idInstituicaoAtualizacao(value:Number):void {
			_idInstituicaoAtualizacao = value;
		}
		
		public function get idPessoa():Number {
			return _idPessoa;
		}
		
		public function set idPessoa(value:Number):void {
			_idPessoa = value;
		}
		
		public function get idPessoaEmpregador():Number {
			return _idPessoaEmpregador;
		}
		
		public function set idPessoaEmpregador(value:Number):void {
			_idPessoaEmpregador = value;
		}
		
		public function get idRegistroControlado():String {
			return _idRegistroControlado;
		}
		
		public function set idRegistroControlado(value:String):void {
			_idRegistroControlado = value;
		}
		
		public function get idUsuarioAprovacao():String{
			return _idUsuarioAprovacao;
		}
		
		public function set idUsuarioAprovacao(valor:String):void{
			_idUsuarioAprovacao = valor;
		}
		
		public function get situacaoAprovacao():SituacaoRegistroEnum {
			if(_situacaoAprovacao == null){
				_situacaoAprovacao = SituacaoRegistroEnum.valueOff(_codigoSituacaoAprovacao);
			}
			return _situacaoAprovacao;
		}
		
		public function set situacaoAprovacao(valor:SituacaoRegistroEnum):void {
			_situacaoAprovacao = valor;
		}
		
		public function get valorReceitaBrutaMensal():Number {
			return _valorReceitaBrutaMensal;
		}
		
		public function set valorReceitaBrutaMensal(value:Number):void {
			_valorReceitaBrutaMensal = value;
		}
		
		public function readExternal(input:IDataInput):void {
			_bolPossuiAtivo					= input.readObject() as Boolean;
			_bolRendaFixa					= input.readObject() as Boolean;
			_bolSimplesNacional				= input.readObject() as Boolean;
			_codigoSituacaoAprovacao		= function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_codigoTipoFonteRenda			= function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_dataHoraInicio					= input.readObject() as IDateTime;
			_dataValidadeRenda				= input.readObject() as IDateTime;
			_descFonteRenda					= input.readObject() as String;
			_descricaoTipoFonteRenda		= input.readObject() as String;
			_idFonteRenda					= function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_idInstituicaoAtualizacao		= function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_idPessoa						= function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_idPessoaEmpregador				= function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_idRegistroControlado			= input.readObject() as String;
			_idUsuarioAprovacao				= input.readObject() as String;
			_situacaoAprovacao				= input.readObject() as SituacaoRegistroEnum;
			_valorReceitaBrutaMensal		= function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
		}
		
		public function writeExternal(output:IDataOutput):void {
			output.writeObject(_bolPossuiAtivo);
			output.writeObject(_bolRendaFixa);
			output.writeObject(_bolSimplesNacional);
			output.writeObject(_codigoSituacaoAprovacao);
			output.writeObject(_codigoTipoFonteRenda);
			output.writeObject(_dataHoraInicio);
			output.writeObject(_dataValidadeRenda);
			output.writeObject(_descFonteRenda);
			output.writeObject(_descricaoTipoFonteRenda);
			output.writeObject(_idFonteRenda);
			output.writeObject(_idInstituicaoAtualizacao);
			output.writeObject(_idPessoa);
			output.writeObject(_idPessoaEmpregador);
			output.writeObject(_idRegistroControlado);
			output.writeObject(_idUsuarioAprovacao);
			output.writeObject(_situacaoAprovacao);
			output.writeObject(_valorReceitaBrutaMensal);
		}
	}
}