/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Mar 02 10:31:07 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (ItemAutorizacaoVO.as).
 */

package br.com.sicoob.capes.comum.vo {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import br.com.sicoob.capes.comum.vo.entidades.AutorizacaoVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class ItemAutorizacaoVOBase {

        private var _atividadeAtual:String;
        private var _autorizacao:AutorizacaoVO;
        private var _idAtividade:Number;
        private var _idOcorrenciaAtividade:Number;
        private var _nomeInstituicao:String;
        private var _numeroCooperativa:Number;

        public function set atividadeAtual(value:String):void {
            _atividadeAtual = value;
        }
        public function get atividadeAtual():String {
            return _atividadeAtual;
        }

        public function set autorizacao(value:AutorizacaoVO):void {
            _autorizacao = value;
        }
        public function get autorizacao():AutorizacaoVO {
            return _autorizacao;
        }

        public function set idAtividade(value:Number):void {
            _idAtividade = value;
        }
        public function get idAtividade():Number {
            return _idAtividade;
        }

        public function set idOcorrenciaAtividade(value:Number):void {
            _idOcorrenciaAtividade = value;
        }
        public function get idOcorrenciaAtividade():Number {
            return _idOcorrenciaAtividade;
        }

        public function set nomeInstituicao(value:String):void {
            _nomeInstituicao = value;
        }
        public function get nomeInstituicao():String {
            return _nomeInstituicao;
        }

        public function set numeroCooperativa(value:Number):void {
            _numeroCooperativa = value;
        }
        public function get numeroCooperativa():Number {
            return _numeroCooperativa;
        }

        public function readExternal(input:IDataInput):void {
	        _atividadeAtual = input.readObject() as String;
	        _autorizacao = input.readObject() as AutorizacaoVO;
            _idAtividade = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _idOcorrenciaAtividade = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
	        _nomeInstituicao = input.readObject() as String;
            _numeroCooperativa = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_atividadeAtual);
            output.writeObject(_autorizacao);
            output.writeObject(_idAtividade);
            output.writeObject(_idOcorrenciaAtividade);
            output.writeObject(_nomeInstituicao);
            output.writeObject(_numeroCooperativa);
        }
    }
}