/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Sep 16 10:07:31 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (PerfilTarifarioVO.as).
 */

package br.com.sicoob.capes.comum.vo{

    import br.com.bancoob.vo.BancoobVO;
    
    public class PerfilTarifarioVOBase extends BancoobVO {

		private var _codPerfilTarifario:Number;
        private var _descricao:String;
        private var _idInstituicao:Number;
        private var _sigla:String;

		public function PerfilTarifarioVOBase() {
			super();
		}
		
        public function set codPerfilTarifario(value:Number):void {
            _codPerfilTarifario = value;
        }
        public function get codPerfilTarifario():Number {
            return _codPerfilTarifario;
        }
		
        public function set idInstituicao(value:Number):void {
            _idInstituicao = value;
        }
        public function get idInstituicao():Number {
            return _idInstituicao;
        }
		
        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set sigla(value:String):void {
            _sigla = value;
        }
        public function get sigla():String {
            return _sigla;
        }

    }
}