/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Jul 13 14:02:54 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (ReferenciaBancariaBaseVO.as).
 */

package br.com.sicoob.capes.comum.vo {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import br.com.sicoob.capes.comum.vo.entidades.ReferenciaVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class ReferenciaBancariaBaseVOBase extends ReferenciaVO {

        private var _numeroAgencia:String;
        private var _numeroBanco:String;
        private var _numeroConta:String;

        public function set numeroAgencia(value:String):void {
            _numeroAgencia = value;
        }
        public function get numeroAgencia():String {
            return _numeroAgencia;
        }

        public function set numeroBanco(value:String):void {
            _numeroBanco = value;
        }
        public function get numeroBanco():String {
            return _numeroBanco;
        }

        public function set numeroConta(value:String):void {
            _numeroConta = value;
        }
        public function get numeroConta():String {
            return _numeroConta;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
                _numeroAgencia = input.readObject() as String;
                _numeroBanco = input.readObject() as String;
                _numeroConta = input.readObject() as String;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
            output.writeObject(_numeroAgencia);
            output.writeObject(_numeroBanco);
            output.writeObject(_numeroConta);
            }
        }
    }
}