/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (ReplicavelVO.as).
 */

package br.com.sicoob.capes.comum.vo {
	import br.com.sicoob.capes.comum.vo.entidades.PessoaCompartilhamentoVO;

    public interface ReplicavelVOBase {

        function get pessoaCompartilhamento():PessoaCompartilhamentoVO;
    }
}