/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Mon Feb 14 16:38:04 GMT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (SumarioAnotacaoVO.as).
 */

package br.com.sicoob.capes.comum.vo {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class SumarioAnotacaoVOBase implements IExternalizable {

        private var _categoria:String;
        private var _dataUltima:Date;
        private var _situacao:String;
        private var _idCategoria:Number;
        private var _idOrigem:Number;
        private var _origem:String;
        private var _quantidade:int;
        private var _valor:Number;

        public function set categoria(value:String):void {
            _categoria = value;
        }
        public function get categoria():String {
            return _categoria;
        }

        public function set dataUltima(value:Date):void {
            _dataUltima = value;
        }
        public function get dataUltima():Date {
            return _dataUltima;
        }

        public function set situacao(value:String):void {
            _situacao = value;
        }
        public function get situacao():String {
            return _situacao;
        }

        public function set idCategoria(value:Number):void {
            _idCategoria = value;
        }
        public function get idCategoria():Number {
            return _idCategoria;
        }

        public function set idOrigem(value:Number):void {
            _idOrigem = value;
        }
        public function get idOrigem():Number {
            return _idOrigem;
        }

        public function set origem(value:String):void {
            _origem = value;
        }
        public function get origem():String {
            return _origem;
        }

        public function set quantidade(value:int):void {
            _quantidade = value;
        }
        public function get quantidade():int {
            return _quantidade;
        }

        public function set valor(value:Number):void {
            _valor = value;
        }
        public function get valor():Number {
            return _valor;
        }

        public function readExternal(input:IDataInput):void {
	        _categoria = input.readObject() as String;
            _dataUltima = SerializacaoObjetos.lerDate(input);
            _idCategoria = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _idOrigem = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
	        _origem = input.readObject() as String;
	        _quantidade = input.readObject() as int;
	        _situacao = input.readObject() as String;
            _valor = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_categoria);
        	SerializacaoObjetos.escreverDate(_dataUltima, output);
            output.writeObject(_idCategoria);
            output.writeObject(_idOrigem);
            output.writeObject(_origem);
            output.writeObject(_quantidade);
            output.writeObject(_situacao);
            output.writeObject(_valor);
        }
    }
}