/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Feb 24 14:57:13 BRT 2012.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TributacaoBaseVO.as).
 */
package br.com.sicoob.capes.comum.vo{

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.IDateTime;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import br.com.sicoob.capes.comum.vo.entidades.EntidadeCadastroBaseVO;

    [Bindable]
    public class TributacaoBaseVOBase extends EntidadeCadastroBaseVO {

        private var _cobrarCPMF:Booleano;
        private var _cobrarIOF:Booleano;
        private var _cobrarIR:Booleano;
		private var _dataHoraInicio:IDateTime;
		
		public function set dataHoraInicio(value:IDateTime):void {
			_dataHoraInicio = value;
		}
		public function get dataHoraInicio():IDateTime {
			return _dataHoraInicio;
		}

        public function set cobrarCPMF(value:Booleano):void {
            _cobrarCPMF = value;
        }
        public function get cobrarCPMF():Booleano {
            return _cobrarCPMF;
        }

        public function set cobrarIOF(value:Booleano):void {
            _cobrarIOF = value;
        }
        public function get cobrarIOF():Booleano {
            return _cobrarIOF;
        }

        public function set cobrarIR(value:Booleano):void {
            _cobrarIR = value;
        }
        public function get cobrarIR():Booleano {
            return _cobrarIR;
        }
		
		public function get idPessoaCompartilhamento():Number {return NaN;}
		public function set idPessoaCompartilhamento(valor:Number):void{}

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
        	_cobrarCPMF = SerializacaoObjetos.lerBooleano(input);
        	_cobrarIOF = SerializacaoObjetos.lerBooleano(input);
        	_cobrarIR = SerializacaoObjetos.lerBooleano(input);
			_dataHoraInicio = input.readObject() as IDateTime;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
        	SerializacaoObjetos.escreverBooleano(_cobrarCPMF, output);
        	SerializacaoObjetos.escreverBooleano(_cobrarIOF, output);
        	SerializacaoObjetos.escreverBooleano(_cobrarIR, output);
			output.writeObject(_dataHoraInicio);        	
        }
    }
}