/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (VigenteVO.as).
 */

package br.com.sicoob.capes.comum.vo {
	import br.com.bancoob.tipos.Booleano;
	import br.com.bancoob.tipos.IDateTime;
	

    public interface VigenteVOBase {

        function set dataHoraInicio(value:IDateTime):void;
        function get dataHoraInicio():IDateTime;

		function set gravarHistorico(gravarHistorico:Booleano):void;
		function get gravarHistorico():Booleano;
    }
}