/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Aug 25 19:23:49 GMT 2010.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (ConsultaSumarioAnotacaoDTO.as).
 */

package br.com.sicoob.capes.cadastrarAnotacao.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class ConsultaSumarioAnotacaoDTOBase implements IExternalizable {


        public function readExternal(input:IDataInput):void {
        }

        public function writeExternal(output:IDataOutput):void {
        }
    }
}