/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Nov 26 16:11:05 GMT 2010.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (DetalheAnotacaoDTO.as).
 */

package br.com.sicoob.capes.cadastrarAnotacao.dto {

    import br.com.bancoob.tipos.IDateTime;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class DetalheAnotacaoDTOBase implements IExternalizable {

        private var _dataOcorrencia:IDateTime;
        private var _valorOcorrencia:Number;

        public function set dataOcorrencia(value:IDateTime):void {
            _dataOcorrencia = value;
        }
        public function get dataOcorrencia():IDateTime {
            return _dataOcorrencia;
        }

        public function set valorOcorrencia(value:Number):void {
            _valorOcorrencia = value;
        }
        public function get valorOcorrencia():Number {
            return _valorOcorrencia;
        }

        public function readExternal(input:IDataInput):void {
            _dataOcorrencia = input.readObject() as IDateTime;
            _valorOcorrencia = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
        	output.writeObject(_dataOcorrencia);
            output.writeObject(_valorOcorrencia);
        }
    }
}