/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Jun 24 15:18:34 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (DetalheAnotacaoSisbrDTO.as).
 */

package br.com.sicoob.capes.cadastrarAnotacao.dto {

    import br.com.bancoob.tipos.IDateTime;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class DetalheAnotacaoSisbrDTOBase extends DetalheAnotacaoDTO {

        private var _contrato:String;
        private var _dataVencimento:IDateTime;
        private var _descricaoModalidade:String;
        private var _descricaoProduto:String;
        private var _numeroCooperativa:String;

        public function set contrato(value:String):void {
            _contrato = value;
        }
        public function get contrato():String {
            return _contrato;
        }

        public function set dataVencimento(value:IDateTime):void {
            _dataVencimento = value;
        }
        public function get dataVencimento():IDateTime {
            return _dataVencimento;
        }

        public function set descricaoModalidade(value:String):void {
            _descricaoModalidade = value;
        }
        public function get descricaoModalidade():String {
            return _descricaoModalidade;
        }

        public function set descricaoProduto(value:String):void {
            _descricaoProduto = value;
        }
        public function get descricaoProduto():String {
            return _descricaoProduto;
        }

        public function set numeroCooperativa(value:String):void {
            _numeroCooperativa = value;
        }
        public function get numeroCooperativa():String {
            return _numeroCooperativa;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
	        _contrato = input.readObject() as String;
            _dataVencimento = input.readObject() as IDateTime;
	        _descricaoModalidade = input.readObject() as String;
	        _descricaoProduto = input.readObject() as String;
	        _numeroCooperativa = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_contrato);
        	output.writeObject(_dataVencimento);
            output.writeObject(_descricaoModalidade);
            output.writeObject(_descricaoProduto);
            output.writeObject(_numeroCooperativa);
        }
    }
}