/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Sep 15 11:09:52 GMT 2010.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (DetalheAcheiDTO.as).
 */

package br.com.sicoob.capes.cadastrarAnotacao.dto {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class DetalheAcheiDTOBase extends DetalheAnotacaoDTO {

        private var _agencia:Number;
        private var _alinea:String;
        private var _banco:String;
        private var _cheque:String;
        private var _cidade:String;
        private var _contaCorrente:String;
        private var _uf:String;

        public function set agencia(value:Number):void {
            _agencia = value;
        }
        public function get agencia():Number {
            return _agencia;
        }

        public function set alinea(value:String):void {
            _alinea = value;
        }
        public function get alinea():String {
            return _alinea;
        }

        public function set banco(value:String):void {
            _banco = value;
        }
        public function get banco():String {
            return _banco;
        }

        public function set cheque(value:String):void {
            _cheque = value;
        }
        public function get cheque():String {
            return _cheque;
        }

        public function set cidade(value:String):void {
            _cidade = value;
        }
        public function get cidade():String {
            return _cidade;
        }

        public function set contaCorrente(value:String):void {
            _contaCorrente = value;
        }
        public function get contaCorrente():String {
            return _contaCorrente;
        }

        public function set uf(value:String):void {
            _uf = value;
        }
        public function get uf():String {
            return _uf;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _agencia = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
	        _alinea = input.readObject() as String;
	        _banco = input.readObject() as String;
	        _cheque = input.readObject() as String;
	        _cidade = input.readObject() as String;
	        _contaCorrente = input.readObject() as String;
	        _uf = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_agencia);
            output.writeObject(_alinea);
            output.writeObject(_banco);
            output.writeObject(_cheque);
            output.writeObject(_cidade);
            output.writeObject(_contaCorrente);
            output.writeObject(_uf);
        }
    }
}