/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Sep 15 11:41:37 GMT 2010.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (DetalheCCFDTO.as).
 */

package br.com.sicoob.capes.cadastrarAnotacao.dto {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class DetalheCCFDTOBase extends DetalheAnotacaoDTO {

        private var _agencia:Number;
        private var _banco:String;
        private var _cidade:String;
        private var _quantidadeCheques:Number;
        private var _uf:String;

        public function set agencia(value:Number):void {
            _agencia = value;
        }
        public function get agencia():Number {
            return _agencia;
        }

        public function set banco(value:String):void {
            _banco = value;
        }
        public function get banco():String {
            return _banco;
        }

        public function set cidade(value:String):void {
            _cidade = value;
        }
        public function get cidade():String {
            return _cidade;
        }

        public function set quantidadeCheques(value:Number):void {
            _quantidadeCheques = value;
        }
        public function get quantidadeCheques():Number {
            return _quantidadeCheques;
        }

        public function set uf(value:String):void {
            _uf = value;
        }
        public function get uf():String {
            return _uf;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _agencia = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
	        _banco = input.readObject() as String;
	        _cidade = input.readObject() as String;
            _quantidadeCheques = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
	        _uf = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_agencia);
            output.writeObject(_banco);
            output.writeObject(_cidade);
            output.writeObject(_quantidadeCheques);
            output.writeObject(_uf);
        }
    }
}