/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Sep 15 11:28:41 GMT 2010.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (DetalheRefinDTO.as).
 */

package br.com.sicoob.capes.cadastrarAnotacao.dto {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class DetalheRefinDTOBase extends DetalheAnotacaoDTO {

        private var _agencia:Number;
        private var _cidade:String;
        private var _cnpjCredor:String;
        private var _codigoEmpresaParticipante:Number;
        private var _natureza:String;
        private var _principal:String;
        private var _uf:String;

        public function set agencia(value:Number):void {
            _agencia = value;
        }
        public function get agencia():Number {
            return _agencia;
        }

        public function set cidade(value:String):void {
            _cidade = value;
        }
        public function get cidade():String {
            return _cidade;
        }

        public function set cnpjCredor(value:String):void {
            _cnpjCredor = value;
        }
        public function get cnpjCredor():String {
            return _cnpjCredor;
        }

        public function set codigoEmpresaParticipante(value:Number):void {
            _codigoEmpresaParticipante = value;
        }
        public function get codigoEmpresaParticipante():Number {
            return _codigoEmpresaParticipante;
        }

        public function set natureza(value:String):void {
            _natureza = value;
        }
        public function get natureza():String {
            return _natureza;
        }

        public function set principal(value:String):void {
            _principal = value;
        }
        public function get principal():String {
            return _principal;
        }

        public function set uf(value:String):void {
            _uf = value;
        }
        public function get uf():String {
            return _uf;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _agencia = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
	        _cidade = input.readObject() as String;
	        _cnpjCredor = input.readObject() as String;
            _codigoEmpresaParticipante = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
	        _natureza = input.readObject() as String;
	        _principal = input.readObject() as String;
	        _uf = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_agencia);
            output.writeObject(_cidade);
            output.writeObject(_cnpjCredor);
            output.writeObject(_codigoEmpresaParticipante);
            output.writeObject(_natureza);
            output.writeObject(_principal);
            output.writeObject(_uf);
        }
    }
}