/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Sep 15 11:12:33 GMT 2010.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (DetalheAcaoDTO.as).
 */

package br.com.sicoob.capes.cadastrarAnotacao.dto {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class DetalheAcaoDTOBase extends DetalheAnotacaoDTO {

        private var _cidade:String;
        private var _natureza:String;
        private var _principal:String;
        private var _uf:String;
        private var _varaCivil:Number;

        public function set cidade(value:String):void {
            _cidade = value;
        }
        public function get cidade():String {
            return _cidade;
        }

        public function set natureza(value:String):void {
            _natureza = value;
        }
        public function get natureza():String {
            return _natureza;
        }

        public function set principal(value:String):void {
            _principal = value;
        }
        public function get principal():String {
            return _principal;
        }

        public function set uf(value:String):void {
            _uf = value;
        }
        public function get uf():String {
            return _uf;
        }

        public function set varaCivil(value:Number):void {
            _varaCivil = value;
        }
        public function get varaCivil():Number {
            return _varaCivil;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
	        _cidade = input.readObject() as String;
	        _natureza = input.readObject() as String;
	        _principal = input.readObject() as String;
	        _uf = input.readObject() as String;
            _varaCivil = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_cidade);
            output.writeObject(_natureza);
            output.writeObject(_principal);
            output.writeObject(_uf);
            output.writeObject(_varaCivil);
        }
    }
}