/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Sep 15 11:53:44 GMT 2010.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (DetalheParticipanteFalidaDTO.as).
 */

package br.com.sicoob.capes.cadastrarAnotacao.dto {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class DetalheParticipanteFalidaDTOBase extends DetalheAnotacaoDTO {

        private var _cnpjEmpresa:String;
        private var _natureza:String;
        private var _nomeEmpresa:String;
        private var _qualificacao:String;
        private var _varaCivil:Number;

        public function set cnpjEmpresa(value:String):void {
            _cnpjEmpresa = value;
        }
        public function get cnpjEmpresa():String {
            return _cnpjEmpresa;
        }

        public function set natureza(value:String):void {
            _natureza = value;
        }
        public function get natureza():String {
            return _natureza;
        }

        public function set nomeEmpresa(value:String):void {
            _nomeEmpresa = value;
        }
        public function get nomeEmpresa():String {
            return _nomeEmpresa;
        }

        public function set qualificacao(value:String):void {
            _qualificacao = value;
        }
        public function get qualificacao():String {
            return _qualificacao;
        }

        public function set varaCivil(value:Number):void {
            _varaCivil = value;
        }
        public function get varaCivil():Number {
            return _varaCivil;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
	        _cnpjEmpresa = input.readObject() as String;
	        _natureza = input.readObject() as String;
	        _nomeEmpresa = input.readObject() as String;
	        _qualificacao = input.readObject() as String;
            _varaCivil = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_cnpjEmpresa);
            output.writeObject(_natureza);
            output.writeObject(_nomeEmpresa);
            output.writeObject(_qualificacao);
            output.writeObject(_varaCivil);
        }
    }
}