/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Tue Mar 29 14:48:51 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (DetalheAnotacaoBacenDTO.as).
 */

package br.com.sicoob.capes.cadastrarAnotacao.dto {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class DetalheAnotacaoBacenDTOBase extends DetalheAnotacaoDTO {

        private var _dataBase:String;
        private var _percentualDocumentosProcessados:Number;
        private var _percentualVolumeProcessado:Number;
        private var _quantidadeInstituicoes:Number;
        private var _quantidadeOperacoes:Number;

        public function set dataBase(value:String):void {
            _dataBase = value;
        }
        public function get dataBase():String {
            return _dataBase;
        }

        public function set percentualDocumentosProcessados(value:Number):void {
            _percentualDocumentosProcessados = value;
        }
        public function get percentualDocumentosProcessados():Number {
            return _percentualDocumentosProcessados;
        }

        public function set percentualVolumeProcessado(value:Number):void {
            _percentualVolumeProcessado = value;
        }
        public function get percentualVolumeProcessado():Number {
            return _percentualVolumeProcessado;
        }

        public function set quantidadeInstituicoes(value:Number):void {
            _quantidadeInstituicoes = value;
        }
        public function get quantidadeInstituicoes():Number {
            return _quantidadeInstituicoes;
        }

        public function set quantidadeOperacoes(value:Number):void {
            _quantidadeOperacoes = value;
        }
        public function get quantidadeOperacoes():Number {
            return _quantidadeOperacoes;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
	        _dataBase = input.readObject() as String;
            _percentualDocumentosProcessados = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _percentualVolumeProcessado = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _quantidadeInstituicoes = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _quantidadeOperacoes = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_dataBase);
            output.writeObject(_percentualDocumentosProcessados);
            output.writeObject(_percentualVolumeProcessado);
            output.writeObject(_quantidadeInstituicoes);
            output.writeObject(_quantidadeOperacoes);
        }
    }
}