/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Jul 27 12:21:15 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RelacionamentoInstituicaoDTO.as).
 */

package br.com.sicoob.capes.cadastrarRelacionamentoInstituicao.dto {

    import br.com.sicoob.capes.comum.vo.entidades.InstituicaoVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class RelacionamentoInstituicaoDTOBase {

        private var _instituicao:InstituicaoVO;
        private var _responsavelCadastro:Boolean;
        
       	public function get nomeInstituicao(): String {
			var valor:String = "";
			if(_instituicao != null) {
				valor = instituicao.numero + " - " + instituicao.nome;
			}
			return valor;
		}        

		public function get numeroUnidadeInst(): String {
			var valor:String = "";
			if(_instituicao != null) {
				valor = new String(instituicao.idUnidadeInst);
			}
			return valor;
		}		

        public function set instituicao(value:InstituicaoVO):void {
            _instituicao = value;
        }
        public function get instituicao():InstituicaoVO {
            return _instituicao;
        }

        public function set responsavelCadastro(value:Boolean):void {
            _responsavelCadastro = value;
        }
        public function get responsavelCadastro():Boolean {
            return _responsavelCadastro;
        }

        public function readExternal(input:IDataInput):void {
	        _instituicao = input.readObject() as InstituicaoVO;
            _responsavelCadastro = input.readBoolean() as Boolean;
        }

		public function writeExternal(output:IDataOutput):void {
            output.writeObject(_instituicao);
			output.writeBoolean(_responsavelCadastro);
        }
    }
}