/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Tue Jan 17 11:40:45 BRST 2012.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (PessoaPlataformaVO.as).
 */

package br.com.sicoob.capes.corporativo.vo {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.IDateTime;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class PessoaPlataformaVOBase implements IExternalizable {

		private var _autorizaConsultaBacen:Boolean;
        private var _codCompartilhamentoCadastro:Number;
        private var _codTipoPessoa:Number;
        private var _cpfCnpj:String;
       	private var _dataInclusaoSFN:IDateTime;
        private var _descTipoPessoa:String;
        private var _idCompartilhamento:Number;
        private var _idInstituicao:Number;
        private var _idPessoa:Number;
		private var _idPessoaInstituicao:Number;
        private var _idPessoaLegado:Number;
        private var _idUnidadeInst:Number;
		private var _isCliente:Booleano;
        private var _nomeApelido:String;
        private var _nomeCompleto:String;
        private var _nomePessoa:String;
		private var _utilizaGedGft:Boolean;
		private var _codigoPerfilCadastro:Number;
        
        // atributo utilizado apenas para realização de filtro
        private var _possuiRelacionamentoBancoob:Boolean;
        

        public function set autorizaConsultaBacen(value:Boolean):void {
            _autorizaConsultaBacen = value;
        }
        public function get autorizaConsultaBacen():Boolean {
            return _autorizaConsultaBacen;
        }
        		
        public function set codCompartilhamentoCadastro(value:Number):void {
            _codCompartilhamentoCadastro = value;
        }
        public function get codCompartilhamentoCadastro():Number {
            return _codCompartilhamentoCadastro;
        }
		
        public function set codTipoPessoa(value:Number):void {
            _codTipoPessoa = value;
        }
        public function get codTipoPessoa():Number {
            return _codTipoPessoa;
        }

        public function set cpfCnpj(value:String):void {
            _cpfCnpj = value;
        }
        public function get cpfCnpj():String {
            return _cpfCnpj;
        }

        public function set dataInclusaoSFN(value:IDateTime):void {
            _dataInclusaoSFN = value;
        }
        public function get dataInclusaoSFN():IDateTime {
            return _dataInclusaoSFN;
        }
        
        public function set descTipoPessoa(value:String):void {
            _descTipoPessoa = value;
        }
        public function get descTipoPessoa():String {
            return _descTipoPessoa;
        }

        public function set idCompartilhamento(value:Number):void {
            _idCompartilhamento = value;
        }
        public function get idCompartilhamento():Number {
            return _idCompartilhamento;
        }

        public function set idInstituicao(value:Number):void {
            _idInstituicao = value;
        }
        public function get idInstituicao():Number {
            return _idInstituicao;
        }

        public function set idPessoa(value:Number):void {
            _idPessoa = value;
        }
        public function get idPessoa():Number {
            return _idPessoa;
        }

		public function get	idPessoaInstituicao() :Number {
			return _idPessoaInstituicao;
		}
		public function set idPessoaInstituicao(value:Number):void {
			_idPessoaInstituicao = value;
		}

        public function set idPessoaLegado(value:Number):void {
            _idPessoaLegado = value;
        }
        public function get idPessoaLegado():Number {
            return _idPessoaLegado;
        }

        public function set idUnidadeInst(value:Number):void {
            _idUnidadeInst = value;
        }
        public function get idUnidadeInst():Number {
            return _idUnidadeInst;
        }
		
		public function get isCliente() : Booleano {
			return _isCliente;
		}
		public function set isCliente(value:Booleano) : void {
			_isCliente = value;
		}

        public function set nomeApelido(value:String):void {
            _nomeApelido = value;
        }
        public function get nomeApelido():String {
            return _nomeApelido;
        }

        public function set nomeCompleto(value:String):void {
            _nomeCompleto = value;
        }
        public function get nomeCompleto():String {
            return _nomeCompleto;
        }

        public function set nomePessoa(value:String):void {
            _nomePessoa = value;
        }
        public function get nomePessoa():String {
            return _nomePessoa;
        }

		public function set possuiRelacionamentoBancoob(value:Boolean):void {
			_possuiRelacionamentoBancoob = value;
		}
		public function get possuiRelacionamentoBancoob():Boolean {
			return _possuiRelacionamentoBancoob;
		}
		
		public function get utilizaGedGft():Boolean {
			return _utilizaGedGft;
		}
		
		public function set utilizaGedGft(value:Boolean):void {
			_utilizaGedGft = value;
		}
		
		public function get codigoPerfilCadastro():Number {
			return _codigoPerfilCadastro;
		}
		
		public function set codigoPerfilCadastro(value:Number):void {
			_codigoPerfilCadastro = value;
		}
		
        public function readExternal(input:IDataInput):void {
        	_autorizaConsultaBacen = input.readObject() as Boolean;
        	_codCompartilhamentoCadastro = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_codigoPerfilCadastro = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _codTipoPessoa = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
	        _cpfCnpj = input.readObject() as String;
	        _dataInclusaoSFN = input.readObject() as IDateTime;
	        _descTipoPessoa = input.readObject() as String;
            _idCompartilhamento = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _idInstituicao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _idPessoa = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _idPessoaLegado = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _idUnidadeInst = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _isCliente = SerializacaoObjetos.lerBooleano(input);
	        _nomeApelido = input.readObject() as String;
	        _nomeCompleto = input.readObject() as String;
	        _nomePessoa = input.readObject() as String;
	        _possuiRelacionamentoBancoob = input.readObject() as Boolean;
			_utilizaGedGft = input.readObject() as Boolean;
        }

        public function writeExternal(output:IDataOutput):void {
        	output.writeObject(_autorizaConsultaBacen);
        	output.writeObject(_codCompartilhamentoCadastro);
        	output.writeObject(_codigoPerfilCadastro);
            output.writeObject(_codTipoPessoa);
            output.writeObject(_cpfCnpj);
            output.writeObject(_dataInclusaoSFN);
            output.writeObject(_descTipoPessoa);
            output.writeObject(_idCompartilhamento);
            output.writeObject(_idInstituicao);
            output.writeObject(_idPessoa);
            output.writeObject(_idPessoaInstituicao);
            output.writeObject(_idPessoaLegado);
            output.writeObject(_idUnidadeInst);
            output.writeObject(_isCliente);
            output.writeObject(_nomeApelido);
            output.writeObject(_nomeCompleto);
            output.writeObject(_nomePessoa);
            output.writeObject(_possuiRelacionamentoBancoob);
            output.writeObject(_utilizaGedGft);
        }
    }
}