/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package br.com.sicoob.capes.corporativo.vo {
	import flash.net.registerClassAlias;

	registerClassAlias("br.com.sicoob.capes.comum.negocio.vo.PessoaPlataformaVO",
			PessoaPlataformaVO);
    public class PessoaPlataformaVO extends PessoaPlataformaVOBase {
    }
}