/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (AprovavelVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades.interfaces {
	import mx.collections.ListCollectionView;

    public interface Comprovavel extends Aprovavel {
		
		function get documentosComprobatorios():ListCollectionView;
		function set documentosComprobatorios(value:ListCollectionView):void;
    }
}