/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Tue Jan 17 11:40:50 BRST 2012.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (AnotacaoVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.IDateTime;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class AnotacaoVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

        private var _codigoTipoExposicao:Number;
        private var _dataHoraAlteracao:IDateTime;
        private var _dataHoraAnotacao:IDateTime;
        private var _dataHoraBaixa:IDateTime;
        private var _dataHoraOcorrencia:IDateTime;
        private var _descObservacao:String;
        private var _flexibilidade:Booleano;
        private var _idAnotacao:Number;
        private var _idConsultaExterna:Number;
        private var _instituicao:InstituicaoVO;
		private var _observacaoAnotacao:ObservacaoAnotacaoVO;
		private var _origemInformacao:OrigemInformacaoVO;
        private var _pessoaCompartilhamento:PessoaCompartilhamentoVO;
        private var _quantidade:Number;
        private var _tipoAnotacao:TipoAnotacaoVO;
        private var _tipoBaixa:TipoBaixaVO;
		private var _tipoConsultaOrigem:TipoConsultaOrigemVO;
        private var _usuarioAlteracao:String;
        private var _usuarioInclusao:String;
        private var _valor:Number;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is AnotacaoVO) || (property as AnotacaoVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set codigoTipoExposicao(value:Number):void {
            _codigoTipoExposicao = value;
        }
        public function get codigoTipoExposicao():Number {
            return _codigoTipoExposicao;
        }

        public function set dataHoraAlteracao(value:IDateTime):void {
            _dataHoraAlteracao = value;
        }
        public function get dataHoraAlteracao():IDateTime {
            return _dataHoraAlteracao;
        }

        public function set dataHoraAnotacao(value:IDateTime):void {
            _dataHoraAnotacao = value;
        }
        public function get dataHoraAnotacao():IDateTime {
            return _dataHoraAnotacao;
        }

        public function set dataHoraBaixa(value:IDateTime):void {
            _dataHoraBaixa = value;
        }
        public function get dataHoraBaixa():IDateTime {
            return _dataHoraBaixa;
        }

        public function set dataHoraOcorrencia(value:IDateTime):void {
            _dataHoraOcorrencia = value;
        }
        public function get dataHoraOcorrencia():IDateTime {
            return _dataHoraOcorrencia;
        }

        public function set descObservacao(value:String):void {
            _descObservacao = value;
        }
        public function get descObservacao():String {
            return _descObservacao;
        }

        public function set flexibilidade(value:Booleano):void {
            _flexibilidade = value;
        }
        public function get flexibilidade():Booleano {
            return _flexibilidade;
        }

        public function set idAnotacao(value:Number):void {
            _idAnotacao = value;
        }
        public function get idAnotacao():Number {
            return _idAnotacao;
        }

        public function set idConsultaExterna(value:Number):void {
            _idConsultaExterna = value;
        }
        public function get idConsultaExterna():Number {
            return _idConsultaExterna;
        }

        public function set instituicao(value:InstituicaoVO):void {
            _instituicao = value;
        }
        public function get instituicao():InstituicaoVO {
            return _instituicao;
        }
		
		public function set observacaoAnotacao(value:ObservacaoAnotacaoVO):void{
			_observacaoAnotacao = value;
		}
		
		public function get observacaoAnotacao():ObservacaoAnotacaoVO{
			return _observacaoAnotacao;
		}
		
		public function get origemInformacao():OrigemInformacaoVO {
			return _origemInformacao;
		}
		
		public function set origemInformacao(valor:OrigemInformacaoVO):void{
			_origemInformacao = valor;
		}

        public function set pessoaCompartilhamento(value:PessoaCompartilhamentoVO):void {
            _pessoaCompartilhamento = value;
        }

        public function set quantidade(value:Number):void {
            _quantidade = value;
        }
        public function get quantidade():Number {
            return _quantidade;
        }

        public function set tipoAnotacao(value:TipoAnotacaoVO):void {
            _tipoAnotacao = value;
        }
        public function get tipoAnotacao():TipoAnotacaoVO {
            return _tipoAnotacao;
        }

        public function set tipoBaixa(value:TipoBaixaVO):void {
            _tipoBaixa = value;
        }
        public function get tipoBaixa():TipoBaixaVO {
            return _tipoBaixa;
        }
		
		public function get tipoConsultaOrigem():TipoConsultaOrigemVO {
			return _tipoConsultaOrigem;
		}
		
		public function set tipoConsultaOrigem(value:TipoConsultaOrigemVO):void {
			_tipoConsultaOrigem = value;
		}

        public function set usuarioAlteracao(value:String):void {
            _usuarioAlteracao = value;
        }
        public function get usuarioAlteracao():String {
            return _usuarioAlteracao;
        }

        public function set usuarioInclusao(value:String):void {
            _usuarioInclusao = value;
        }
        public function get usuarioInclusao():String {
            return _usuarioInclusao;
        }

        public function set valor(value:Number):void {
            _valor = value;
        }
        public function get valor():Number {
            return _valor;
        }

        public function get pessoaCompartilhamento():PessoaCompartilhamentoVO {
            return _pessoaCompartilhamento;
        }
		
		public function get origemInfoTipoConsulta():String{
			var retorno:String = "";
			if(origemInformacao != null){
				retorno = retorno + origemInformacao.descOrigemInfo;
			}
			
			if(tipoConsultaOrigem != null){
				retorno = retorno + " - " + tipoConsultaOrigem.nomeTipoConsultaOrigem;
			}
			
			return retorno
		}

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
                _codigoTipoExposicao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            	_dataHoraAlteracao = input.readObject() as IDateTime;
            	_dataHoraAnotacao = input.readObject() as IDateTime;
            	_dataHoraBaixa = input.readObject() as IDateTime;
            	_dataHoraOcorrencia = input.readObject() as IDateTime;
                _descObservacao = input.readObject() as String;
            	_flexibilidade = SerializacaoObjetos.lerBooleano(input);
                _idAnotacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _idConsultaExterna = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _instituicao = input.readObject() as InstituicaoVO;
				_observacaoAnotacao = input.readObject() as ObservacaoAnotacaoVO;
				_origemInformacao = input.readObject() as OrigemInformacaoVO;
                _pessoaCompartilhamento = input.readObject() as PessoaCompartilhamentoVO;
                _quantidade = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _tipoAnotacao = input.readObject() as TipoAnotacaoVO;
                _tipoBaixa = input.readObject() as TipoBaixaVO;
				_tipoConsultaOrigem = input.readObject() as TipoConsultaOrigemVO;
                _usuarioAlteracao = input.readObject() as String;
                _usuarioInclusao = input.readObject() as String;
                _valor = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
            else {
                _idAnotacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
            output.writeObject(_codigoTipoExposicao);
        	output.writeObject(_dataHoraAlteracao);
        	output.writeObject(_dataHoraAnotacao);
        	output.writeObject(_dataHoraBaixa);
        	output.writeObject(_dataHoraOcorrencia);
            output.writeObject(_descObservacao);
        	SerializacaoObjetos.escreverBooleano(_flexibilidade, output);
            output.writeObject(_idAnotacao);
            output.writeObject(_idConsultaExterna);
            output.writeObject(_instituicao);
			output.writeObject(_observacaoAnotacao);
            output.writeObject(_origemInformacao);
            output.writeObject(_pessoaCompartilhamento);
            output.writeObject(_quantidade);
            output.writeObject(_tipoAnotacao);
            output.writeObject(_tipoBaixa);
            output.writeObject(_tipoConsultaOrigem);
            output.writeObject(_usuarioAlteracao);
            output.writeObject(_usuarioInclusao);
            output.writeObject(_valor);
            }
            else {
                output.writeObject(_idAnotacao);
            }
        }
    }
}