/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package br.com.sicoob.capes.comum.vo.entidades {

	import flash.net.registerClassAlias;

	registerClassAlias("br.com.sicoob.capes.negocio.entidades.Autorizacao",
			AutorizacaoVO);
    public class AutorizacaoVO extends AutorizacaoVOBase {
		
		public function get cooperativaOrigem() : String {
			return instituicaoOrigem.numero + '-' 
				+ (instituicaoOrigem.idUnidadeInst >= 10 ? '' : '0') + instituicaoOrigem.idUnidadeInst;  
		}
		
		public function get cooperativaDestino() : String {
			return instituicaoDestino.numero + '-' 
				+ (instituicaoDestino.idUnidadeInst >= 10 ? '' : '0') + instituicaoDestino.idUnidadeInst;  
		}
    }
}