/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Mon Feb 07 10:49:21 GMT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (AutorizacaoVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.IDateTime;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import br.com.sicoob.capes.comum.enums.TipoAutorizacaoEnum;
    import br.com.sicoob.capes.comum.enums.TipoOperacaoEnum;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ListCollectionView;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class AutorizacaoVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

        private var _alteracao:String;
		private var _dataHoraCadastro:IDateTime;
        private var _dataHoraSolicitacao:IDateTime;
		private var _devolvido:Booleano;
		private var _documentos:ListCollectionView;
        private var _idAutorizacao:Number;
        private var _idRegistroAntigo:Number;
        private var _idRegistroControlado:String;
        private var _idRegistroNovo:Number;
        private var _instituicaoDestino:InstituicaoVO;
        private var _instituicaoOrigem:InstituicaoVO;
		private var _nomePessoa:String;
        private var _pessoa:PessoaVO;
		private var _siglaProcesso:String;
        private var _tipoAutorizacao:TipoAutorizacaoEnum;
        private var _tipoOperacao:TipoOperacaoEnum;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is AutorizacaoVO) || (property as AutorizacaoVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set alteracao(value:String):void {
            _alteracao = value;
        }
        public function get alteracao():String {
            return _alteracao;
        }

        public function set dataHoraCadastro(value:IDateTime):void {
            _dataHoraCadastro = value;
        }
        public function get dataHoraCadastro():IDateTime {
            return _dataHoraCadastro;
        }

        public function set dataHoraSolicitacao(value:IDateTime):void {
            _dataHoraSolicitacao = value;
        }
        public function get dataHoraSolicitacao():IDateTime {
            return _dataHoraSolicitacao;
        }
		
		public function set devolvido(value:Booleano):void {
			_devolvido = value;
		}
		public function get devolvido():Booleano {
			return _devolvido;
		}
		
		public function set documentos(value:ListCollectionView):void {
			_documentos = value;
		}
		public function get documentos():ListCollectionView {
			return _documentos;
		}

        public function set idAutorizacao(value:Number):void {
            _idAutorizacao = value;
        }
        public function get idAutorizacao():Number {
            return _idAutorizacao;
        }

        public function set idRegistroAntigo(value:Number):void {
            _idRegistroAntigo = value;
        }
        public function get idRegistroAntigo():Number {
            return _idRegistroAntigo;
        }

        public function set idRegistroControlado(value:String):void {
            _idRegistroControlado = value;
        }
        public function get idRegistroControlado():String {
            return _idRegistroControlado;
        }

        public function set idRegistroNovo(value:Number):void {
            _idRegistroNovo = value;
        }
        public function get idRegistroNovo():Number {
            return _idRegistroNovo;
        }

        public function set instituicaoDestino(value:InstituicaoVO):void {
            _instituicaoDestino = value;
        }
        public function get instituicaoDestino():InstituicaoVO {
            return _instituicaoDestino;
        }

        public function set instituicaoOrigem(value:InstituicaoVO):void {
            _instituicaoOrigem = value;
        }
        public function get instituicaoOrigem():InstituicaoVO {
            return _instituicaoOrigem;
        }
		
		public function set nomePessoa(value:String):void{
			_nomePessoa = value;
		}
		public function get nomePessoa():String{
			return _nomePessoa;
		}

        public function set pessoa(value:PessoaVO):void {
            _pessoa = value;
        }
        public function get pessoa():PessoaVO {
            return _pessoa;
        }

		public function set siglaProcesso(value:String):void {
			_siglaProcesso = value;
		}
		public function get siglaProcesso():String {
			return _siglaProcesso;
		}
		
        public function set tipoAutorizacao(value:TipoAutorizacaoEnum):void {
            _tipoAutorizacao = value;
        }
        public function get tipoAutorizacao():TipoAutorizacaoEnum {
            return _tipoAutorizacao;
        }

        public function set tipoOperacao(value:TipoOperacaoEnum):void {
            _tipoOperacao = value;
        }
        public function get tipoOperacao():TipoOperacaoEnum {
            return _tipoOperacao;
        }

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
                _alteracao = input.readObject() as String;
            	_dataHoraCadastro = input.readObject() as IDateTime;
            	_dataHoraSolicitacao = input.readObject() as IDateTime;
				_devolvido = SerializacaoObjetos.lerBooleano(input);
            	_documentos = input.readObject() as ListCollectionView;
                _idAutorizacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _idRegistroAntigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _idRegistroControlado = input.readObject() as String;
                _idRegistroNovo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _instituicaoDestino = input.readObject() as InstituicaoVO;
                _instituicaoOrigem = input.readObject() as InstituicaoVO;
				_nomePessoa = input.readObject() as String;
                _pessoa = input.readObject() as PessoaVO;
				_siglaProcesso = input.readObject() as String;
                _tipoAutorizacao = input.readObject() as TipoAutorizacaoEnum;
                _tipoOperacao = input.readObject() as TipoOperacaoEnum;
            }
            else {
                _idAutorizacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
	            output.writeObject(_alteracao);
				output.writeObject(_dataHoraCadastro);
				output.writeObject(_dataHoraSolicitacao);
				SerializacaoObjetos.escreverBooleano(_devolvido, output);
				output.writeObject(_documentos);
	            output.writeObject(_idAutorizacao);
	            output.writeObject(_idRegistroAntigo);
	            output.writeObject(_idRegistroControlado);
	            output.writeObject(_idRegistroNovo);
	            output.writeObject(_instituicaoDestino);
	            output.writeObject(_instituicaoOrigem);
				output.writeObject(_nomePessoa);
	            output.writeObject(_pessoa);
				output.writeObject(_siglaProcesso);
	            output.writeObject(_tipoAutorizacao);
	            output.writeObject(_tipoOperacao);
            }
            else {
                output.writeObject(_idAutorizacao);
            }
        }
    }
}