/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Mon Aug 23 18:35:05 GMT 2010.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (CAPESEntidadeVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class CAPESEntidadeVOBase implements IExternalizable {


        public function readExternal(input:IDataInput):void {
        }

        public function writeExternal(output:IDataOutput):void {
        }
    }
}