/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Dec 02 14:36:46 BRST 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (CategoriaProdutorVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class CategoriaProdutorVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

		private var _ativo:Boolean;
        private var _codigo:Number;
        private var _descricao:String;
        private var _valorLimite:Number;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is CategoriaProdutorVO) || (property as CategoriaProdutorVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }
		
		public function set ativo(value:Boolean):void {
			_ativo = value;
		}
		public function get ativo():Boolean {
			return _ativo;
		}

        public function set codigo(value:Number):void {
            _codigo = value;
        }
        public function get codigo():Number {
            return _codigo;
        }

        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set valorLimite(value:Number):void {
            _valorLimite = value;
        }
        public function get valorLimite():Number {
            return _valorLimite;
        }

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
				_ativo = input.readObject() as Boolean;
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _descricao = input.readObject() as String;
                _valorLimite = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
            else {
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
			output.writeObject(_ativo);
            output.writeObject(_codigo);
            output.writeObject(_descricao);
            output.writeObject(_valorLimite);
            }
            else {
                output.writeObject(_codigo);
            }
        }
    }
}