/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Thu Aug 25 16:07:07 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (CnaeFiscalVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class CnaeFiscalVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

        private var _cnaePai:CnaeFiscalVO;
        private var _codigo:String;
        private var _descricao:String;
        private var _tipoClassificacao:String;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is CnaeFiscalVO) || (property as CnaeFiscalVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set cnaePai(value:CnaeFiscalVO):void {
            _cnaePai = value;
        }
        public function get cnaePai():CnaeFiscalVO {
            return _cnaePai;
        }

        public function set codigo(value:String):void {
            _codigo = value;
        }
        public function get codigo():String {
            return _codigo;
        }

        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set tipoClassificacao(value:String):void {
            _tipoClassificacao = value;
        }
        public function get tipoClassificacao():String {
            return _tipoClassificacao;
        }

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
                _cnaePai = input.readObject() as CnaeFiscalVO;
                _codigo = input.readObject() as String;
                _descricao = input.readObject() as String;
                _tipoClassificacao = input.readObject() as String;
            }
            else {
                _codigo = input.readObject() as String;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
            output.writeObject(_cnaePai);
            output.writeObject(_codigo);
            output.writeObject(_descricao);
            output.writeObject(_tipoClassificacao);
            }
            else {
                output.writeObject(_codigo);
            }
        }
    }
}