/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Thu Oct 20 16:50:07 BRST 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (DadosRegistroRelacionamentoVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.negocio.entidades.BancoobEmbeddableObject;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class DadosRegistroRelacionamentoVOBase extends BancoobEmbeddableObject {

        private var _nomeCartorio:String;
        private var _numeroFolha:String;
        private var _numeroLivro:String;
        private var _numeroRegistro:String;

        public function set nomeCartorio(value:String):void {
            _nomeCartorio = value;
        }
        public function get nomeCartorio():String {
            return _nomeCartorio;
        }

        public function set numeroFolha(value:String):void {
            _numeroFolha = value;
        }
        public function get numeroFolha():String {
            return _numeroFolha;
        }

        public function set numeroLivro(value:String):void {
            _numeroLivro = value;
        }
        public function get numeroLivro():String {
            return _numeroLivro;
        }

        public function set numeroRegistro(value:String):void {
            _numeroRegistro = value;
        }
        public function get numeroRegistro():String {
            return _numeroRegistro;
        }

        override public function readExternal(input:IDataInput):void {
	        _nomeCartorio = input.readObject() as String;
	        _numeroFolha = input.readObject() as String;
	        _numeroLivro = input.readObject() as String;
	        _numeroRegistro = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(_nomeCartorio);
            output.writeObject(_numeroFolha);
            output.writeObject(_numeroLivro);
            output.writeObject(_numeroRegistro);
        }
    }
}