/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Thu May 19 14:46:18 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (EmailBaseVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.IDateTime;
    import br.com.sicoob.capes.comum.vo.entidades.EntidadeCadastroBaseVO;
    import br.com.sicoob.capes.comum.vo.entidades.PessoaCompartilhamentoVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class EmailBaseVOBase extends EntidadeCadastroBaseVO {

		private var _dataHoraInicio:IDateTime;
        private var _descricao:String;
        private var _pessoaCompartilhamento:PessoaCompartilhamentoVO;
        private var _tipoEmail:TipoEmailVO;
		
		public function set dataHoraInicio(value:IDateTime):void {
			_dataHoraInicio = value;
		}
		public function get dataHoraInicio():IDateTime {
			return _dataHoraInicio;
		}

		public function get descricaoTipoEmail(): String {
			var valor:String = "";
			if(_tipoEmail != null) {
				valor = _tipoEmail.descricao;
			}
			return valor;
		}
		
        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set pessoaCompartilhamento(value:PessoaCompartilhamentoVO):void {
            _pessoaCompartilhamento = value;
        }
        public function get pessoaCompartilhamento():PessoaCompartilhamentoVO {
            return _pessoaCompartilhamento;
        }

        public function set tipoEmail(value:TipoEmailVO):void {
            _tipoEmail = value;
        }
        public function get tipoEmail():TipoEmailVO {
            return _tipoEmail;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
			_dataHoraInicio = input.readObject() as IDateTime;
            _descricao = input.readObject() as String;
            _pessoaCompartilhamento = input.readObject() as PessoaCompartilhamentoVO;
            _tipoEmail = input.readObject() as TipoEmailVO;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
			output.writeObject(_dataHoraInicio);        	
           	output.writeObject(_descricao);
            output.writeObject(_pessoaCompartilhamento);
            output.writeObject(_tipoEmail);
        }
    }
}