/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Dec 02 14:36:46 BRST 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (EmpreendimentoVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class EmpreendimentoVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

		private var _ativo:Booleano;
        private var _codigo:Number;
		private var _codigoBacen:String;
        private var _descricao:String;
        private var _exigeArea:Booleano;
        private var _exigeImovel:Booleano;
        private var _finalidade:FinalidadeEmpreendimentoVO;
        private var _unidadeArea:UnidadeMedidaVO;
        private var _unidadePrevisao:UnidadeMedidaVO;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is EmpreendimentoVO) || (property as EmpreendimentoVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

		public function set ativo(value:Booleano):void {
			_ativo = value;
		}
		public function get ativo():Booleano {
			return _ativo;
		}
		
        public function set codigo(value:Number):void {
            _codigo = value;
        }
        public function get codigo():Number {
            return _codigo;
        }

		public function set codigoBacen(value:String):void {
			_codigoBacen = value;
		}
		public function get codigoBacen():String {
			return _codigoBacen;
		}
		
        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set exigeArea(value:Booleano):void {
            _exigeArea = value;
        }
        public function get exigeArea():Booleano {
            return _exigeArea;
        }

        public function set exigeImovel(value:Booleano):void {
            _exigeImovel = value;
        }
        public function get exigeImovel():Booleano {
            return _exigeImovel;
        }

        public function set finalidade(value:FinalidadeEmpreendimentoVO):void {
            _finalidade = value;
        }
        public function get finalidade():FinalidadeEmpreendimentoVO {
            return _finalidade;
        }

        public function set unidadeArea(value:UnidadeMedidaVO):void {
            _unidadeArea = value;
        }
        public function get unidadeArea():UnidadeMedidaVO {
            return _unidadeArea;
        }

        public function set unidadePrevisao(value:UnidadeMedidaVO):void {
            _unidadePrevisao = value;
        }
        public function get unidadePrevisao():UnidadeMedidaVO {
            return _unidadePrevisao;
        }

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
				_ativo = SerializacaoObjetos.lerBooleano(input);
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_codigoBacen = input.readObject() as String;
                _descricao = input.readObject() as String;
            	_exigeArea = SerializacaoObjetos.lerBooleano(input);
            	_exigeImovel = SerializacaoObjetos.lerBooleano(input);
                _finalidade = input.readObject() as FinalidadeEmpreendimentoVO;
                _unidadeArea = input.readObject() as UnidadeMedidaVO;
                _unidadePrevisao = input.readObject() as UnidadeMedidaVO;
            }
            else {
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
				SerializacaoObjetos.escreverBooleano(_ativo, output);
	            output.writeObject(_codigo);
				output.writeObject(_codigoBacen);
	            output.writeObject(_descricao);
	        	SerializacaoObjetos.escreverBooleano(_exigeArea, output);
	        	SerializacaoObjetos.escreverBooleano(_exigeImovel, output);
	            output.writeObject(_finalidade);
	            output.writeObject(_unidadeArea);
	            output.writeObject(_unidadePrevisao);
            }
            else {
                output.writeObject(_codigo);
            }
        }
    }
}