/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Tue Jan 17 11:40:45 BRST 2012.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (EnderecoProxy.as).
 */
package br.com.sicoob.capes.comum.vo.entidades {
	
	import br.com.bancoob.tipos.IDateTime;
	import br.com.sicoob.capes.comum.enums.SituacaoRegistroEnum;
	
	import flash.utils.IDataInput;
	import flash.utils.IDataOutput;
	
	[Bindable]
	public class EnderecoProxyBase /*implements IExternalizable*/ {
		
		private var _bairro:String;
		private var _codigoSituacaoAprovacao:Number;
		private var _complemento:String;
		private var _cooperativasCorrespondencia:String;
		private var _dataHoraInicio:IDateTime;
		private var _descricaoEndereco:String;
		private var _descricaoTipoEndereco:String;
		private var _idEndereco:Number;
		private var _idInstituicaoAtualizacao:Number;
		private var _idRegistroControlado:String;
		private var _idUsuarioAprovacao:String;
		private var _nomeCidade:String;
		private var _numero:String;
		private var _padraoCorrespondencia:Boolean;
		private var _siglaUF:String;
		private var _situacaoAprovacao:br.com.sicoob.capes.comum.enums.SituacaoRegistroEnum;
		
		public function get idEndereco():Number {
			return _idEndereco;
		}
		
		public function set idEndereco(value:Number):void {
			_idEndereco = value;
		}
		
		public function set codigoSituacaoAprovacao(value:Number):void{
			_codigoSituacaoAprovacao = value;
		}
		
		public function get codigoSituacaoAprovacao():Number {
			return _codigoSituacaoAprovacao;
		}
		
		public function get complemento():String {
			return _complemento;
		}
		
		public function set complemento(valor:String):void{
			_complemento = valor;
		}
		
		public function get idInstituicaoAtualizacao():Number {
			return _idInstituicaoAtualizacao;
		}
		
		public function set idInstituicaoAtualizacao(value:Number):void {
			_idInstituicaoAtualizacao = value;
		}
		
		public function get dataHoraInicio():IDateTime {
			return _dataHoraInicio;
		}
		
		public function set dataHoraInicio(value:IDateTime):void {
			_dataHoraInicio = value;
		}
		
		public function get descricaoTipoEndereco():String {
			return _descricaoTipoEndereco;
		}
		
		public function set descricaoTipoEndereco(value:String):void {
			_descricaoTipoEndereco = value;
		}
		
		public function get descricaoEndereco():String {
			return _descricaoEndereco;
		}
		
		public function set descricaoEndereco(value:String):void {
			_descricaoEndereco = value;
		}
		
		public function get numero():String {
			return _numero;
		}
		
		public function set numero(value:String):void {
			_numero = value;
		}
		
		public function get bairro():String {
			return _bairro;
		}
		
		public function set bairro(value:String):void {
			_bairro = value;
		}
		
		public function get nomeCidade():String {
			return _nomeCidade;
		}
		
		public function set nomeCidade(value:String):void {
			_nomeCidade = value;
		}
		
		public function get siglaUF():String {
			return _siglaUF;
		}
		
		public function set siglaUF(value:String):void {
			_siglaUF = value;
		}
		
		public function get padraoCorrespondencia():Boolean {
			return _padraoCorrespondencia;
		}
		
		public function set padraoCorrespondencia(value:Boolean):void {
			_padraoCorrespondencia = value;
		}
		
		public function get cooperativasCorrespondencia():String {
			return _cooperativasCorrespondencia;
		}
		
		public function set cooperativasCorrespondencia(value:String):void {
			_cooperativasCorrespondencia = value;
		}
		
		public function get idRegistroControlado():String{
			return _idRegistroControlado;
		}
		
		public function set idRegistroControlado(valor:String):void{
			_idRegistroControlado = valor;
		}
		
		public function get idUsuarioAprovacao():String{
			return _idUsuarioAprovacao;
		}
		
		public function set idUsuarioAprovacao(valor:String):void{
			_idUsuarioAprovacao = valor;
		}
		
		public function get situacaoAprovacao():SituacaoRegistroEnum {
			if(_situacaoAprovacao == null){
				_situacaoAprovacao = SituacaoRegistroEnum.valueOff(_codigoSituacaoAprovacao);
			}
			return _situacaoAprovacao;
		}
		
		public function set situacaoAprovacao(valor:SituacaoRegistroEnum):void {
			_situacaoAprovacao = valor;
		}
		
		public function readExternal(input:IDataInput):void {
			_bairro 						= input.readObject() as String;
			_codigoSituacaoAprovacao 		= function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_complemento 					= input.readObject() as String;
			_cooperativasCorrespondencia 	= input.readObject() as String;
			_dataHoraInicio					= input.readObject() as IDateTime;
			_descricaoEndereco 				= input.readObject() as String;
			_descricaoTipoEndereco 			= input.readObject() as String;
			_idEndereco 					= function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_idInstituicaoAtualizacao		= function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_idRegistroControlado			= input.readObject() as String;
			_idUsuarioAprovacao				= input.readObject() as String;
			_nomeCidade 					= input.readObject() as String;
			_numero 						= input.readObject() as String;
			_padraoCorrespondencia			= input.readObject() as Boolean;
			_siglaUF 						= input.readObject() as String;
			_situacaoAprovacao 				= input.readObject() as SituacaoRegistroEnum;
		}
		
		public function writeExternal(output:IDataOutput):void {
			output.writeObject(_bairro);
			output.writeObject(_codigoSituacaoAprovacao);
			output.writeObject(_complemento);
			output.writeObject(_cooperativasCorrespondencia);
			output.writeObject(_dataHoraInicio);
			output.writeObject(_descricaoEndereco);
			output.writeObject(_descricaoTipoEndereco);
			output.writeObject(_idEndereco);
			output.writeObject(_idInstituicaoAtualizacao);
			output.writeObject(_idRegistroControlado);
			output.writeObject(_idUsuarioAprovacao);
			output.writeObject(_nomeCidade);
			output.writeObject(_numero);
			output.writeObject(_padraoCorrespondencia);
			output.writeObject(_siglaUF);
			output.writeObject(_situacaoAprovacao);
		}
	}
}