/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Mon Feb 07 10:55:11 GMT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (EntidadeCadastroBaseVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class EntidadeCadastroBaseVOBase extends CAPESEntidadeVO {
		
		private var _idUsuarioAprovacao:String;
		private var _idUsuarioExclusao:String;
		
		public function get idUsuarioAprovacao():String{
			return _idUsuarioAprovacao;
		}
		
		public function set idUsuarioAprovacao(valor:String):void{
			this._idUsuarioAprovacao = valor;
		}
		
		public function get idUsuarioExclusao():String {
			return _idUsuarioExclusao;
		}
		
		public function set idUsuarioExclusao(value:String):void{
			_idUsuarioExclusao = value;
		}
		
		override public function readExternal(input:IDataInput):void {
			super.readExternal(input);
			_idUsuarioAprovacao = input.readObject() as String;
			_idUsuarioExclusao = input.readObject() as String;
		}
		
		override public function writeExternal(output:IDataOutput):void {
			output.writeObject(_idUsuarioAprovacao);
			output.writeObject(_idUsuarioExclusao);
		}
	}
}