/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */
package br.com.sicoob.capes.comum.vo.entidades {

	import flash.net.registerClassAlias;

	registerClassAlias("br.com.sicoob.capes.negocio.entidades.EntidadeCadastroBase",
			EntidadeCadastroBaseVO);
    public class EntidadeCadastroBaseVO extends EntidadeCadastroBaseVOBase {
		
//		public function get pessoaCompartilhamento():PessoaCompartilhamentoVO {
//			return null;
//		}
		
//		public function get idRegistroControlado():String {
//			var idRegistroControlado : String = null;
//			if (this is AprovavelVO) {
//				var aprovavel : AprovavelVO = this as AprovavelVO;
//				var tipoAutorizacao : TipoAutorizacaoEnum = aprovavel.tipoAutorizacao;
//				idRegistroControlado = tipoAutorizacao.name + "#" + aprovavel.id;
//			}
//			return idRegistroControlado;
//		}
    }
}