/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Jan 25 09:49:10 BRST 2012.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (FonteRendaBaseVO.as).
 */
package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.IDateTime;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class FonteRendaBaseVOBase extends EntidadeCadastroBaseVO {

		private var _bolPossuiAtivo:Booleano;
        private var _bolRendaFixa:Booleano;
		private var _bolSimplesNacional:Booleano;
		private var _dataHoraInicio:IDateTime;
        private var _dataValidadeRenda:IDateTime;
        private var _descFonteRenda:String;
        private var _pessoaCompartilhamento:PessoaCompartilhamentoVO;
        private var _pessoaEmpregador:PessoaCompartilhamentoVO;
        private var _tipoFonteRenda:TipoFonteRendaVO;
        private var _valorReceitaBrutaMensal:Number;
		
		public function set dataHoraInicio(value:IDateTime):void {
			_dataHoraInicio = value;
		}
		public function get dataHoraInicio():IDateTime {
			return _dataHoraInicio;
		}
		
		public function set bolPossuiAtivo(value:Booleano):void {
			_bolPossuiAtivo = value;
		}
		public function get bolPossuiAtivo():Booleano {
			return _bolPossuiAtivo;
		}
		
		public function set bolRendaFixa(value:Booleano):void {
			_bolRendaFixa = value;
		}
		public function get bolRendaFixa():Booleano {
			return _bolRendaFixa;
		}
		
		public function set bolSimplesNacional(value:Booleano):void {
			_bolSimplesNacional = value;
		}
		public function get bolSimplesNacional():Booleano {
			return _bolSimplesNacional;
		}

        public function set dataValidadeRenda(value:IDateTime):void {
            _dataValidadeRenda = value;
        }
        public function get dataValidadeRenda():IDateTime {
            return _dataValidadeRenda;
        }

        public function set descFonteRenda(value:String):void {
            _descFonteRenda = value;
        }
        public function get descFonteRenda():String {
            return _descFonteRenda;
        }

        public function set pessoaCompartilhamento(value:PessoaCompartilhamentoVO):void {
            _pessoaCompartilhamento = value;
        }
        public function get pessoaCompartilhamento():PessoaCompartilhamentoVO {
            return _pessoaCompartilhamento;
        }

        public function set pessoaEmpregador(value:PessoaCompartilhamentoVO):void {
            _pessoaEmpregador = value;
        }
        public function get pessoaEmpregador():PessoaCompartilhamentoVO {
            return _pessoaEmpregador;
        }

        public function set tipoFonteRenda(value:TipoFonteRendaVO):void {
            _tipoFonteRenda = value;
        }
        public function get tipoFonteRenda():TipoFonteRendaVO {
            return _tipoFonteRenda;
        }

        public function set valorReceitaBrutaMensal(value:Number):void {
            _valorReceitaBrutaMensal = value;
        }
        public function get valorReceitaBrutaMensal():Number {
            return _valorReceitaBrutaMensal;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
			_bolPossuiAtivo = SerializacaoObjetos.lerBooleano(input);
        	_bolRendaFixa = SerializacaoObjetos.lerBooleano(input);
			_bolSimplesNacional = SerializacaoObjetos.lerBooleano(input);
			_dataHoraInicio = input.readObject() as IDateTime;
        	_dataValidadeRenda = input.readObject() as IDateTime;
            _descFonteRenda = input.readObject() as String;
            _pessoaCompartilhamento = input.readObject() as PessoaCompartilhamentoVO;
            _pessoaEmpregador = input.readObject() as PessoaCompartilhamentoVO;
            _tipoFonteRenda = input.readObject() as TipoFonteRendaVO;
            _valorReceitaBrutaMensal = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
			SerializacaoObjetos.escreverBooleano(_bolPossuiAtivo, output);
        	SerializacaoObjetos.escreverBooleano(_bolRendaFixa, output);
			SerializacaoObjetos.escreverBooleano(_bolSimplesNacional, output);
			output.writeObject(_dataHoraInicio);        	
	       	output.writeObject(_dataValidadeRenda);
            output.writeObject(_descFonteRenda);
            output.writeObject(_pessoaCompartilhamento);
            output.writeObject(_pessoaEmpregador);
            output.writeObject(_tipoFonteRenda);
            output.writeObject(_valorReceitaBrutaMensal);
        }
    }
}