/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Sep 16 15:57:19 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (FuncaoVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades{

    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class FuncaoVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

        private var _descricao:String;
        private var _idFuncao:Number;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is FuncaoVO) || (property as FuncaoVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set idFuncao(value:Number):void {
            _idFuncao = value;
        }
        public function get idFuncao():Number {
            return _idFuncao;
        }

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
                _descricao = input.readObject() as String;
                _idFuncao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
            else {
                _idFuncao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
            output.writeObject(_descricao);
            output.writeObject(_idFuncao);
            }
            else {
                output.writeObject(_idFuncao);
            }
        }
    }
}