/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Thu Apr 12 15:17:43 BRT 2012.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (FuncionarioVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.IDateTime;
    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    import br.com.sicoob.capes.comum.vo.entidades.InstituicaoVO;
    import br.com.sicoob.capes.comum.vo.entidades.PessoaVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class FuncionarioVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

        private var _dataAdmissao:IDateTime;
        private var _dataDesligamento:IDateTime;
        private var _funcao:FuncaoVO;
        private var _idFuncionario:Number;
        private var _instituicao:InstituicaoVO;
        private var _matricula:String;
        private var _nucleo:NucleoVO;
        private var _pessoa:PessoaVO;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is FuncionarioVO) || (property as FuncionarioVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set dataAdmissao(value:IDateTime):void {
            _dataAdmissao = value;
        }
        public function get dataAdmissao():IDateTime {
            return _dataAdmissao;
        }

        public function set dataDesligamento(value:IDateTime):void {
            _dataDesligamento = value;
        }
        public function get dataDesligamento():IDateTime {
            return _dataDesligamento;
        }

        public function set funcao(value:FuncaoVO):void {
            _funcao = value;
        }
        public function get funcao():FuncaoVO {
            return _funcao;
        }

        public function set idFuncionario(value:Number):void {
            _idFuncionario = value;
        }
        public function get idFuncionario():Number {
            return _idFuncionario;
        }

        public function set instituicao(value:InstituicaoVO):void {
            _instituicao = value;
        }
        public function get instituicao():InstituicaoVO {
            return _instituicao;
        }

        public function set matricula(value:String):void {
            _matricula = value;
        }
        public function get matricula():String {
            return _matricula;
        }

        public function set nucleo(value:NucleoVO):void {
            _nucleo = value;
        }
        public function get nucleo():NucleoVO {
            return _nucleo;
        }

        public function set pessoa(value:PessoaVO):void {
            _pessoa = value;
        }
        public function get pessoa():PessoaVO {
            return _pessoa;
        }

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
            	_dataAdmissao = input.readObject() as IDateTime;
            	_dataDesligamento = input.readObject() as IDateTime;
                _funcao = input.readObject() as FuncaoVO;
                _idFuncionario = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _instituicao = input.readObject() as InstituicaoVO;
                _matricula = input.readObject() as String;
                _nucleo = input.readObject() as NucleoVO;
                _pessoa = input.readObject() as PessoaVO;
            }
            else {
                _idFuncionario = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
	        	output.writeObject(_dataAdmissao);
	        	output.writeObject(_dataDesligamento);
	            output.writeObject(_funcao);
	            output.writeObject(_idFuncionario);
	            output.writeObject(_instituicao);
	            output.writeObject(_matricula);
	            output.writeObject(_nucleo);
	            output.writeObject(_pessoa);
            }
            else {
                output.writeObject(_idFuncionario);
            }
        }
    }
}