/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Sep 16 10:07:31 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (GrupoEconomicoVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades{

    import br.com.bancoob.tipos.IDateTime;
    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ListCollectionView;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class GrupoEconomicoVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

		private var _dataHoraCadastro:IDateTime;
		private var _dataHoraExclusao:IDateTime;
        private var _descricao:String;
        private var _idGrupoEconomico:Number;
        private var _idInstituicao:Number;
        private var _integrantes:ListCollectionView;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is GrupoEconomicoVO) || (property as GrupoEconomicoVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

		public function set dataHoraCadastro(value:IDateTime):void {
			_dataHoraCadastro = value;
		}
		public function get dataHoraCadastro():IDateTime {
			return _dataHoraCadastro;
		}
		
		public function set dataHoraExclusao(value:IDateTime):void {
			_dataHoraExclusao = value;
		}
		public function get dataHoraExclusao():IDateTime {
			return _dataHoraExclusao;
		}
		
        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set idGrupoEconomico(value:Number):void {
            _idGrupoEconomico = value;
        }
        public function get idGrupoEconomico():Number {
            return _idGrupoEconomico;
        }

        public function set idInstituicao(value:Number):void {
            _idInstituicao = value;
        }
        public function get idInstituicao():Number {
            return _idInstituicao;
        }

        public function set integrantes(value:ListCollectionView):void {
            _integrantes = value;
        }
        public function get integrantes():ListCollectionView {
            return _integrantes;
        }

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
                _dataHoraCadastro = input.readObject() as IDateTime;
                _dataHoraExclusao = input.readObject() as IDateTime;
                _descricao = input.readObject() as String;
                _idGrupoEconomico = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _idInstituicao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _integrantes = input.readObject() as ListCollectionView;
            }
            else {
                _idGrupoEconomico = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
                output.writeObject(_dataHoraCadastro);
                output.writeObject(_dataHoraExclusao);
	            output.writeObject(_descricao);
	            output.writeObject(_idGrupoEconomico);
	            output.writeObject(_idInstituicao);
	            output.writeObject(_integrantes);
            }
            else {
                output.writeObject(_idGrupoEconomico);
            }
        }
    }
}