/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Thu Sep 15 10:23:37 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (LocalidadeVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.negocio.entidades.BancoobEmbeddableObject;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class LocalidadeVOBase extends BancoobEmbeddableObject {

		private var _codigoIBGE:String;
        private var _idLocalidade:Number;
        private var _nome:String;
		private var _nomeLimpo:String;
		private var _numeroCep:String;
        private var _uf:UFVO;
		
		public function get codigoIBGE():String {
			return _codigoIBGE;
		}
		
		public function set codigoIBGE(value:String):void {
			_codigoIBGE = value;
		}

        public function set idLocalidade(value:Number):void {
            _idLocalidade = value;
        }
        public function get idLocalidade():Number {
            return _idLocalidade;
        }

        public function set nome(value:String):void {
            _nome = value;
        }
        public function get nome():String {
            return _nome;
        }
		
		public function get nomeLimpo():String {
			return _nomeLimpo;
		}
		
		public function set nomeLimpo(value:String):void {
			_nomeLimpo = value;
		}
		
		public function get numeroCep():String {
			return _numeroCep;
		}
		
		public function set numeroCep(value:String):void {
			_numeroCep = value;
		}
		
        public function set uf(value:UFVO):void {
            _uf = value;
        }
        public function get uf():UFVO {
            return _uf;
        }

        override public function readExternal(input:IDataInput):void {
			_codigoIBGE = input.readObject() as String;
            _idLocalidade = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
	        _nome = input.readObject() as String;
			_nomeLimpo = input.readObject() as String;
			_numeroCep = input.readObject() as String;
	        _uf = input.readObject() as UFVO;
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(_codigoIBGE);
            output.writeObject(_idLocalidade);
            output.writeObject(_nome);
            output.writeObject(_nomeLimpo);
            output.writeObject(_numeroCep);
            output.writeObject(_uf);
        }
    }
}