/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Tue Aug 02 14:23:50 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (MensagemVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import br.com.sicoob.capes.comum.vo.ReplicavelVO;
    import br.com.sicoob.capes.comum.vo.VigenteVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class MensagemVOBase extends MensagemBaseVO implements ReplicavelVO, VigenteVO {

        private var __laziness:String = null;

		private var _gravarHistorico:Booleano = new Booleano(true);
		
        private var _idMensagem:Number;
		private var _tipoDestinoExibicao:TipoDestinoExibicaoVO;
		private var _tipoMensagem:TipoMensagemVO;
		
        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is MensagemVO) || (property as MensagemVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }
		
		public function set gravarHistorico(value:Booleano):void {
			_gravarHistorico = value;
		}
		public function get gravarHistorico():Booleano {
			return _gravarHistorico;
		}

        public function set idMensagem(value:Number):void {
            _idMensagem = value;
        }
        public function get idMensagem():Number {
            return _idMensagem;
        }
		
		public function get pessoaCompartilhamento():PessoaCompartilhamentoVO {
			return this.pessoa.compartilhamentos[0];
		}
		
		public function set tipoDestinoExibicao(value:TipoDestinoExibicaoVO):void {
			_tipoDestinoExibicao = value;
		}
		
		public function get tipoDestinoExibicao():TipoDestinoExibicaoVO {
			return _tipoDestinoExibicao;
		}
		
		public function set tipoMensagem(value:TipoMensagemVO):void {
			_tipoMensagem = value;
		}
		
		public function get tipoMensagem():TipoMensagemVO {
			return _tipoMensagem;
		}

				
        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
				_gravarHistorico = SerializacaoObjetos.lerBooleano(input);
                _idMensagem = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_tipoDestinoExibicao = input.readObject() as TipoDestinoExibicaoVO;
				_tipoMensagem = input.readObject() as TipoMensagemVO; 
            }
            else {
                _idMensagem = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
				SerializacaoObjetos.escreverBooleano(_gravarHistorico, output);
	            output.writeObject(_idMensagem);
				output.writeObject(_tipoDestinoExibicao);
				output.writeObject(_tipoMensagem);
            }
            else {
                output.writeObject(_idMensagem);
            }
        }
    }
}