/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Sep 16 10:07:31 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (NucleoVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades{

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class NucleoVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

		private var _ativo:Booleano;
        private var _descricao:String;
        private var _idInstituicao:Number;
        private var _idNucleo:Number;
        private var _numNucleo:Number;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is NucleoVO) || (property as NucleoVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }
		
		public function set ativo(value:Booleano):void {
			_ativo = value;
		}
		public function get ativo():Booleano {
			return _ativo;
		}

        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set idInstituicao(value:Number):void {
            _idInstituicao = value;
        }
        public function get idInstituicao():Number {
            return _idInstituicao;
        }

        public function set idNucleo(value:Number):void {
            _idNucleo = value;
        }
        public function get idNucleo():Number {
            return _idNucleo;
        }
        
        public function set numNucleo(value:Number):void {
            _numNucleo = value;
        }
        public function get numNucleo():Number {
            return _numNucleo;
        }
        
        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
				_ativo = SerializacaoObjetos.lerBooleano(input);
                _descricao = input.readObject() as String;
                _idInstituicao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _idNucleo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _numNucleo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
            else {
                _idNucleo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
			SerializacaoObjetos.escreverBooleano(_ativo, output);
            output.writeObject(_descricao);
            output.writeObject(_idInstituicao);
            output.writeObject(_idNucleo);
            output.writeObject(_numNucleo);
            }
            else {
                output.writeObject(_idNucleo);
            }
        }
    }
}