/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Mon Jan 17 12:52:22 GMT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (OrigemInformacaoVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class OrigemInformacaoVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

        private var _descOrigemInfo:String;
        private var _idOrigemInfo:Number;
		private var _nomeOrigemInfo:String;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is OrigemInformacaoVO) || (property as OrigemInformacaoVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set descOrigemInfo(value:String):void {
            _descOrigemInfo = value;
        }
        public function get descOrigemInfo():String {
            return _descOrigemInfo;
        }

        public function set idOrigemInfo(value:Number):void {
            _idOrigemInfo = value;
        }
        public function get idOrigemInfo():Number {
            return _idOrigemInfo;
        }
		
		public function get nomeOrigemInfo():String{
			return _nomeOrigemInfo;	
		}
		
		public function set nomeOrigemInfo(valor:String):void{
			_nomeOrigemInfo = valor;
		}

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
                _descOrigemInfo = input.readObject() as String;
                _idOrigemInfo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_nomeOrigemInfo = input.readObject() as String;
            }
            else {
                _idOrigemInfo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
            output.writeObject(_descOrigemInfo);
            output.writeObject(_idOrigemInfo);
            output.writeObject(_nomeOrigemInfo);
            }
            else {
                output.writeObject(_idOrigemInfo);
            }
        }
    }
}