/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Sep 16 10:07:31 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (PerfilTarifarioVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades{

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import br.com.sicoob.capes.comum.vo.entidades.pk.PerfilTarifarioPK;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class PerfilTarifarioVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

		private var _codigoTipoPerfil:Number;
        private var _codTipoPerfilConta:Number;
        private var _codTipoPercentual:Number;
        private var _descricao:String;
        private var _isento:Booleano;
        private var _pk:PerfilTarifarioPK;
        private var _sigla:String;
        private var _valorPercentual:Number;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is PerfilTarifarioVO) || (property as PerfilTarifarioVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }
		
        public function set codigoTipoPerfil(value:Number):void {
            _codigoTipoPerfil = value;
        }
        public function get codigoTipoPerfil():Number {
            return _codigoTipoPerfil;
        }
		
        public function set pk(value:PerfilTarifarioPK):void {
            _pk = value;
        }
        public function get pk():PerfilTarifarioPK {
            return _pk;
        }
		
        public function set codTipoPerfilConta(value:Number):void {
            _codTipoPerfilConta = value;
        }
        public function get codTipoPerfilConta():Number {
            return _codTipoPerfilConta;
        }

        public function set codTipoPercentual(value:Number):void {
            _codTipoPercentual = value;
        }
        public function get codTipoPercentual():Number {
            return _codTipoPercentual;
        }

        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set isento(value:Booleano):void {
            _isento = value;
        }
        public function get isento():Booleano {
            return _isento;
        }

        public function set sigla(value:String):void {
            _sigla = value;
        }
        public function get sigla():String {
            return _sigla;
        }

        public function set valorPercentual(value:Number):void {
            _valorPercentual = value;
        }
        public function get valorPercentual():Number {
            return _valorPercentual;
        }
		
		public function get codigoDescricao():String {
			return pk.codPerfilTarifario + " - " + descricao;
		}

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
                _codigoTipoPerfil = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _codTipoPercentual = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _codTipoPerfilConta = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _descricao = input.readObject() as String;
            	_isento = SerializacaoObjetos.lerBooleano(input);
                _pk = input.readObject() as PerfilTarifarioPK;
                _sigla = input.readObject() as String;
                _valorPercentual = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
            else {
                _pk = input.readObject() as PerfilTarifarioPK;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
	            output.writeObject(_codigoTipoPerfil);
	            output.writeObject(_codTipoPercentual);
	            output.writeObject(_codTipoPerfilConta);
	            output.writeObject(_descricao);
	        	SerializacaoObjetos.escreverBooleano(_isento, output);
	            output.writeObject(_pk);
	            output.writeObject(_sigla);
	            output.writeObject(_valorPercentual);
            }
            else {
                output.writeObject(_pk);
            }
        }
    }
}