/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Tue Jan 17 09:51:01 BRST 2012.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (PessoaJuridicaVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.IDateTime;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class PessoaJuridicaVOBase extends PessoaCompartilhamentoVO {

        private var _codigoEsferaAdministrativa:Number;
        private var _contratoSocial:String;
        private var _dataConstituicao:IDateTime;
        private var _dataRegistroJuntaComercial:IDateTime;
        private var _dataRegistroRepresentacao:IDateTime;
        private var _dataUltimaAlteracaoContratoSocial:IDateTime;
        private var _formaConstituicao:TipoFormaConstituicaoVO;
        private var _inscricaoEstadual:String;
		private var _nacionalidade:NacionalidadeVO;
        private var _numeroRegistroJuntaComercial:String;
        private var _numeroRegistroRepresentacao:String;
        private var _numeroUltimaAlteracaoContratoSocial:String;
        private var _tipoEmpresa:TipoEmpresaVO;
        private var _valorCapitalSocial:Number;
		private var _inscricaoMunicipal:String;

        public function set codigoEsferaAdministrativa(value:Number):void {
            _codigoEsferaAdministrativa = value;
        }
        public function get codigoEsferaAdministrativa():Number {
            return _codigoEsferaAdministrativa;
        }

        public function set contratoSocial(value:String):void {
            _contratoSocial = value;
        }
        public function get contratoSocial():String {
            return _contratoSocial;
        }

        public function set dataConstituicao(value:IDateTime):void {
            _dataConstituicao = value;
        }
        public function get dataConstituicao():IDateTime {
            return _dataConstituicao;
        }

        public function set dataRegistroJuntaComercial(value:IDateTime):void {
            _dataRegistroJuntaComercial = value;
        }
        public function get dataRegistroJuntaComercial():IDateTime {
            return _dataRegistroJuntaComercial;
        }

        public function set dataRegistroRepresentacao(value:IDateTime):void {
            _dataRegistroRepresentacao = value;
        }
        public function get dataRegistroRepresentacao():IDateTime {
            return _dataRegistroRepresentacao;
        }

        public function set dataUltimaAlteracaoContratoSocial(value:IDateTime):void {
            _dataUltimaAlteracaoContratoSocial = value;
        }
        public function get dataUltimaAlteracaoContratoSocial():IDateTime {
            return _dataUltimaAlteracaoContratoSocial;
        }

        public function set formaConstituicao(value:TipoFormaConstituicaoVO):void {
            _formaConstituicao = value;
        }
        public function get formaConstituicao():TipoFormaConstituicaoVO {
            return _formaConstituicao;
        }

        public function set inscricaoEstadual(value:String):void {
            _inscricaoEstadual = value;
        }
        public function get inscricaoEstadual():String {
            return _inscricaoEstadual;
        }
		
		public function set nacionalidade(value:NacionalidadeVO):void {
			_nacionalidade = value;
		}
		public function get nacionalidade():NacionalidadeVO {
			return _nacionalidade;
		}

        public function set numeroRegistroJuntaComercial(value:String):void {
            _numeroRegistroJuntaComercial = value;
        }
        public function get numeroRegistroJuntaComercial():String {
            return _numeroRegistroJuntaComercial;
        }

        public function set numeroRegistroRepresentacao(value:String):void {
            _numeroRegistroRepresentacao = value;
        }
        public function get numeroRegistroRepresentacao():String {
            return _numeroRegistroRepresentacao;
        }

        public function set numeroUltimaAlteracaoContratoSocial(value:String):void {
            _numeroUltimaAlteracaoContratoSocial = value;
        }
        public function get numeroUltimaAlteracaoContratoSocial():String {
            return _numeroUltimaAlteracaoContratoSocial;
        }

        public function set tipoEmpresa(value:TipoEmpresaVO):void {
            _tipoEmpresa = value;
        }
        public function get tipoEmpresa():TipoEmpresaVO {
            return _tipoEmpresa;
        }

        public function set valorCapitalSocial(value:Number):void {
            _valorCapitalSocial = value;
        }
        public function get valorCapitalSocial():Number {
            return _valorCapitalSocial;
        }
		
		public function set inscricaoMunicipal(value:String):void {
			_inscricaoMunicipal = value;
		}
		
		public function get inscricaoMunicipal():String {
			return _inscricaoMunicipal;
		}

		
        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
                _codigoEsferaAdministrativa = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _contratoSocial = input.readObject() as String;
            	_dataConstituicao = input.readObject() as IDateTime;
            	_dataRegistroJuntaComercial = input.readObject() as IDateTime;
            	_dataRegistroRepresentacao = input.readObject() as IDateTime;
            	_dataUltimaAlteracaoContratoSocial = input.readObject() as IDateTime;
                _formaConstituicao = input.readObject() as TipoFormaConstituicaoVO;
                _inscricaoEstadual = input.readObject() as String;
				_inscricaoMunicipal = input.readObject() as String;
				_nacionalidade = input.readObject() as NacionalidadeVO;
                _numeroRegistroJuntaComercial = input.readObject() as String;
                _numeroRegistroRepresentacao = input.readObject() as String;
                _numeroUltimaAlteracaoContratoSocial = input.readObject() as String;
                _tipoEmpresa = input.readObject() as TipoEmpresaVO;
                _valorCapitalSocial = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
            output.writeObject(_codigoEsferaAdministrativa);
            output.writeObject(_contratoSocial);
        	output.writeObject(_dataConstituicao);
        	output.writeObject(_dataRegistroJuntaComercial);
        	output.writeObject(_dataRegistroRepresentacao);
        	output.writeObject(_dataUltimaAlteracaoContratoSocial);
            output.writeObject(_formaConstituicao);
            output.writeObject(_inscricaoEstadual);
			output.writeObject(_inscricaoMunicipal);
			output.writeObject(_nacionalidade);
            output.writeObject(_numeroRegistroJuntaComercial);
            output.writeObject(_numeroRegistroRepresentacao);
            output.writeObject(_numeroUltimaAlteracaoContratoSocial);
            output.writeObject(_tipoEmpresa);
            output.writeObject(_valorCapitalSocial);
            }
        }
    }
}