/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Mon Feb 27 09:39:15 BRT 2012.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (PessoaInstituicaoVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades{

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    [Bindable]
    public class PessoaInstituicaoVOBase extends PessoaInstituicaoBaseVO {

        private var __laziness:String = null;

        private var _gravarHistorico:Booleano;
        private var _idPessoaInstituicao:Number;
        private var _trocarGrupo:Booleano;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is PessoaInstituicaoVO) || (property as PessoaInstituicaoVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set gravarHistorico(value:Booleano):void {
            _gravarHistorico = value;
        }
        public function get gravarHistorico():Booleano {
            return _gravarHistorico;
        }

        public function set idPessoaInstituicao(value:Number):void {
            _idPessoaInstituicao = value;
        }
        public function get idPessoaInstituicao():Number {
            return _idPessoaInstituicao;
        }
		
		public function set trocarGrupo(value:Booleano):void {
			_trocarGrupo = value;
		}
		public function get trocarGrupo():Booleano {
			return _trocarGrupo;
		}
		
        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
            	_gravarHistorico = SerializacaoObjetos.lerBooleano(input);
                _idPessoaInstituicao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _trocarGrupo = SerializacaoObjetos.lerBooleano(input);
            }
            else {
                _idPessoaInstituicao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
	        	SerializacaoObjetos.escreverBooleano(_gravarHistorico, output);
	            output.writeObject(_idPessoaInstituicao);
	            SerializacaoObjetos.escreverBooleano(_trocarGrupo, output);
            }
            else {
                output.writeObject(_idPessoaInstituicao);
            }
        }
    }
}