/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Tue Jan 17 09:51:01 BRST 2012.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (PessoaCompartilhamentoVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ListCollectionView;
    
    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.IDateTime;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import br.com.sicoob.capes.comum.enums.SituacaoRegistroEnum;
    import br.com.sicoob.capes.comum.enums.TipoAutorizacaoEnum;
    import br.com.sicoob.capes.comum.vo.VigenteVO;
    import br.com.sicoob.capes.comum.vo.entidades.PerfilCadastroVO;
    import br.com.sicoob.capes.comum.vo.entidades.interfaces.Comprovavel;
    
    import org.granite.meta;
    import org.granite.collections.IPersistentCollection;

    use namespace meta;

    [Bindable]
    public class PessoaCompartilhamentoVOBase extends EntidadeCadastroBaseVO implements VigenteVO, Comprovavel {

        private var __laziness:String = null;

        private var _atividadeEconomica:AtividadeEconomicaVO;
        private var _autorizaConsultaBacen:Booleano = new Booleano(false);
        private var _cnae:CnaeFiscalVO;
        private var _codCompartilhamentoCadastro:Number;
		private var _codigoSituacaoAprovacao:Number;
		private var _codigoTipoAtualizacaoRenovacao:Number;
        private var _compartilhamento:CompartilhamentoCadastroVO;
		private var _dataHoraInicio:IDateTime;
        private var _dataInclusaoSFN:IDateTime;
        private var _dataInclusaoSistema:IDateTime;
		private var _dataRenovacaoCadastral:IDateTime;
        private var _descricao:String;
		private var _documentosComprobatorios:ListCollectionView;
        private var _gravarHistorico:Booleano;
		private var _idInstituicaoAtualizacao:Number;
        private var _idPessoaCompartilhamento:Number;
		private var _idRegistroControlado:String;
		private var _idUsuarioEnvio:String;
        private var _nomeApelido:String;
        private var _nomeCompleto:String;
        private var _nomePessoa:String;
		private var _perfilCadastro:PerfilCadastroVO;
        private var _pessoa:PessoaVO;
		private var _situacaoAprovacao:SituacaoRegistroEnum;
        private var _transicoes:ListCollectionView;
		private var _verificarAutorizacao:Booleano = new Booleano(true);
		private var _idUsuarioRenovacao:String;
		private var _idInstituicaoRenovacao:Number;
		private var _idCooperativaRenovacao:Number;
		private var _exportador:Booleano = new Booleano(false);
		private var _importador:Booleano = new Booleano(false);


        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is PessoaCompartilhamentoVO) || (property as PessoaCompartilhamentoVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }
		
		public function set codigoSituacaoAprovacao(valor:Number):void{
			_codigoSituacaoAprovacao = valor;
		}
		
		public function get codigoSituacaoAprovacao():Number {
			return _codigoSituacaoAprovacao;
		}
		
		public function set situacaoAprovacao(valor:SituacaoRegistroEnum):void{
			_situacaoAprovacao = valor;
		}
		
		public function get situacaoAprovacao():SituacaoRegistroEnum {
			if(_situacaoAprovacao == null){
				_situacaoAprovacao = SituacaoRegistroEnum.valueOff(_codigoSituacaoAprovacao);
			}
			return _situacaoAprovacao;
		}
		
		public function set documentosComprobatorios(value:ListCollectionView):void {
			_documentosComprobatorios = value;
		}
		public function get documentosComprobatorios():ListCollectionView {
			return _documentosComprobatorios;
		}
		
		public function set idInstituicaoAtualizacao(value:Number):void {
			_idInstituicaoAtualizacao = value;
		}
		public function get idInstituicaoAtualizacao():Number {
			return _idInstituicaoAtualizacao;
		}
		
		public function get verificarAutorizacao():Booleano {
			return _verificarAutorizacao;
		}
		public function set verificarAutorizacao(value:Booleano):void {
			_verificarAutorizacao = value;
		}
		
		public function set dataHoraInicio(value:IDateTime):void {
			_dataHoraInicio = value;
		}
		public function get dataHoraInicio():IDateTime {
			return _dataHoraInicio;
		}

        public function set atividadeEconomica(value:AtividadeEconomicaVO):void {
            _atividadeEconomica = value;
        }
        public function get atividadeEconomica():AtividadeEconomicaVO {
            return _atividadeEconomica;
        }

        public function set autorizaConsultaBacen(value:Booleano):void {
            _autorizaConsultaBacen = value;
        }
        public function get autorizaConsultaBacen():Booleano {
            return _autorizaConsultaBacen;
        }

        public function set cnae(value:CnaeFiscalVO):void {
            _cnae = value;
        }
        public function get cnae():CnaeFiscalVO {
            return _cnae;
        }

        public function set codCompartilhamentoCadastro(value:Number):void {
            _codCompartilhamentoCadastro = value;
        }
        public function get codCompartilhamentoCadastro():Number {
            return _codCompartilhamentoCadastro;
        }

        public function set compartilhamento(value:CompartilhamentoCadastroVO):void {
            _compartilhamento = value;
        }
        public function get compartilhamento():CompartilhamentoCadastroVO {
            return _compartilhamento;
        }

        public function set dataInclusaoSFN(value:IDateTime):void {
            _dataInclusaoSFN = value;
        }
        public function get dataInclusaoSFN():IDateTime {
            return _dataInclusaoSFN;
        }

        public function set dataInclusaoSistema(value:IDateTime):void {
            _dataInclusaoSistema = value;
        }
        public function get dataInclusaoSistema():IDateTime {
            return _dataInclusaoSistema;
        }

        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set gravarHistorico(value:Booleano):void {
            _gravarHistorico = value;
        }
        public function get gravarHistorico():Booleano {
            return _gravarHistorico;
        }

        public function set idPessoaCompartilhamento(value:Number):void {
            _idPessoaCompartilhamento = value;
        }
        public function get idPessoaCompartilhamento():Number {
            return _idPessoaCompartilhamento;
        }
		
		public function set idRegistroControlado(value:String):void {
			_idRegistroControlado = value;
		}
		public function get idRegistroControlado():String {
			if(_idRegistroControlado == null){
				_idRegistroControlado = tipoAutorizacao.name + "#" + id;
			}
			return _idRegistroControlado;
		}

        public function set nomeApelido(value:String):void {
            _nomeApelido = value;
        }
        public function get nomeApelido():String {
            return _nomeApelido;
        }

        public function set nomeCompleto(value:String):void {
            _nomeCompleto = value;
        }
        public function get nomeCompleto():String {
            return _nomeCompleto;
        }

        public function set nomePessoa(value:String):void {
            _nomePessoa = value;
        }
        public function get nomePessoa():String {
            return _nomePessoa;
        }
		public function set perfilCadastro(value:PerfilCadastroVO):void {
			_perfilCadastro = value;
		}
		public function get perfilCadastro():PerfilCadastroVO {
			return _perfilCadastro;
		}
        public function set pessoa(value:PessoaVO):void {
            _pessoa = value;
        }
        public function get pessoa():PessoaVO {
            return _pessoa;
        }

        public function set transicoes(value:ListCollectionView):void {
            _transicoes = value;
        }
        public function get transicoes():ListCollectionView {
            return _transicoes;
        }

		public function get tipoAutorizacao():TipoAutorizacaoEnum {
			return TipoAutorizacaoEnum.PESSOA;
		}
		
		public function get id():Number {
			return _idPessoaCompartilhamento;
		}
		
		public function get idInstituicaoRenovacao():Number
		{
			return _idInstituicaoRenovacao;
		}
		
		public function set idInstituicaoRenovacao(value:Number):void
		{
			_idInstituicaoRenovacao = value;
		}
		
		public function get idUsuarioRenovacao():String
		{
			return _idUsuarioRenovacao;
		}
		
		public function set idUsuarioRenovacao(value:String):void
		{
			_idUsuarioRenovacao = value;
		}
		
		public function get dataRenovacaoCadastral():IDateTime
		{
			return _dataRenovacaoCadastral;
		}
		
		public function set dataRenovacaoCadastral(value:IDateTime):void
		{
			_dataRenovacaoCadastral = value;
		}
		
		public function get idCooperativaRenovacao():Number
		{
			return _idCooperativaRenovacao;
		}
		
		public function set idCooperativaRenovacao(value:Number):void
		{
			_idCooperativaRenovacao = value;
		}
		
		public function get codigoTipoAtualizacaoRenovacao():Number
		{
			return _codigoTipoAtualizacaoRenovacao;
		}
		
		public function set codigoTipoAtualizacaoRenovacao(value:Number):void
		{
			_codigoTipoAtualizacaoRenovacao = value;
		}
		
		public function get importador():Booleano
		{
			return _importador;
		}
		
		public function set importador(value:Booleano):void
		{
			_importador = value;
		}
		
		public function get exportador():Booleano
		{
			return _exportador;
		}
		
		public function set exportador(value:Booleano):void
		{
			_exportador = value;
		}
		
		public function get idUsuarioEnvio():String
		{
			return _idUsuarioEnvio;
		}
		
		public function set idUsuarioEnvio(value:String):void
		{
			_idUsuarioEnvio = value; 	
		}
		
		public function get pessoaCompartilhamento():PessoaCompartilhamentoVO {
			var retorno:PessoaCompartilhamentoVO = null;
			if (this is PessoaCompartilhamentoVO) {
				retorno = PessoaCompartilhamentoVO(this);
			}
			return retorno;
		}
		
        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
                _atividadeEconomica = input.readObject() as AtividadeEconomicaVO;
            	_autorizaConsultaBacen = SerializacaoObjetos.lerBooleano(input);
                _cnae = input.readObject() as CnaeFiscalVO;
                _codCompartilhamentoCadastro = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_codigoSituacaoAprovacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_codigoTipoAtualizacaoRenovacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _compartilhamento = input.readObject() as CompartilhamentoCadastroVO;
				_dataHoraInicio = input.readObject() as IDateTime;
            	_dataInclusaoSFN = input.readObject() as IDateTime;
            	_dataInclusaoSistema = input.readObject() as IDateTime;
				_dataRenovacaoCadastral = input.readObject() as IDateTime;
                _descricao = input.readObject() as String;
	            _documentosComprobatorios = input.readObject() as ListCollectionView;
				_exportador = SerializacaoObjetos.lerBooleano(input);
            	_gravarHistorico = SerializacaoObjetos.lerBooleano(input);
				_idCooperativaRenovacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
	            _idInstituicaoAtualizacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_idInstituicaoRenovacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _idPessoaCompartilhamento = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_idRegistroControlado = input.readObject() as String;
				_idUsuarioEnvio  = input.readObject() as String;
				_idUsuarioRenovacao = input.readObject() as String;
				_importador = SerializacaoObjetos.lerBooleano(input);
				_nomeApelido = input.readObject() as String;
                _nomeCompleto = input.readObject() as String;
                _nomePessoa = input.readObject() as String;
				_perfilCadastro = input.readObject() as PerfilCadastroVO;
                _pessoa = input.readObject() as PessoaVO;
				_situacaoAprovacao = input.readObject() as SituacaoRegistroEnum;
                _transicoes = input.readObject() as ListCollectionView;
				_verificarAutorizacao = SerializacaoObjetos.lerBooleano(input);
            }
            else {
                _idPessoaCompartilhamento = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
				
	            output.writeObject(_atividadeEconomica);
	        	SerializacaoObjetos.escreverBooleano(_autorizaConsultaBacen, output);
				output.writeObject(_cnae);
				output.writeObject(_codCompartilhamentoCadastro);
				output.writeObject(_codigoSituacaoAprovacao);
				output.writeObject(_codigoTipoAtualizacaoRenovacao);
				output.writeObject(_compartilhamento);
				output.writeObject(_dataHoraInicio);
				output.writeObject(_dataInclusaoSFN);
				output.writeObject(_dataInclusaoSistema);
				output.writeObject(_dataRenovacaoCadastral);
				output.writeObject(_descricao);
				output.writeObject(_documentosComprobatorios);
				SerializacaoObjetos.escreverBooleano(_exportador, output);
				SerializacaoObjetos.escreverBooleano(_gravarHistorico, output);
				output.writeObject(_idCooperativaRenovacao);
				output.writeObject(isNaN(_idInstituicaoAtualizacao) ? null : _idInstituicaoAtualizacao);
				output.writeObject(_idInstituicaoRenovacao);
				output.writeObject(_idPessoaCompartilhamento);
				output.writeObject(_idRegistroControlado);
				output.writeObject(_idUsuarioEnvio);
				output.writeObject(_idUsuarioRenovacao);
				SerializacaoObjetos.escreverBooleano(_importador, output);
				output.writeObject(_nomeApelido);
				output.writeObject(_nomeCompleto);
				output.writeObject(_nomePessoa);
				output.writeObject(_perfilCadastro);
				output.writeObject(_pessoa);
				output.writeObject(_situacaoAprovacao);
				output.writeObject(_transicoes);
				SerializacaoObjetos.escreverBooleano(_verificarAutorizacao, output);
            }
            else {
                output.writeObject(_idPessoaCompartilhamento);
            }
        }
    }
}