/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Dec 02 14:36:43 BRST 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (ProdutorBaseVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import br.com.bancoob.tipos.IDateTime;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class ProdutorBaseVOBase extends EntidadeCadastroBaseVO {

        private var _categoria:CategoriaProdutorVO;
        private var _codigoInscricao:String;
		private var _dataHoraInicio:IDateTime;
		private var _idUsuarioEnvio:String;
        private var _mesAnoPermanente:String;
        private var _mesAnoTemporario:String;
        private var _qtdPermanente:Number;
        private var _qtdTemporario:Number;
		private var _tipoBeneficiarioSicor:TipoBeneficiarioSicorVO;
		
		public function set dataHoraInicio(value:IDateTime):void {
			_dataHoraInicio = value;
		}
		public function get dataHoraInicio():IDateTime {
			return _dataHoraInicio;
		}

        public function set categoria(value:CategoriaProdutorVO):void {
            _categoria = value;
        }
        public function get categoria():CategoriaProdutorVO {
            return _categoria;
        }

        public function set codigoInscricao(value:String):void {
            _codigoInscricao = value;
        }
        public function get codigoInscricao():String {
            return _codigoInscricao;
        }

        public function set mesAnoPermanente(value:String):void {
            _mesAnoPermanente = value;
        }
        public function get mesAnoPermanente():String {
            return _mesAnoPermanente;
        }

        public function set mesAnoTemporario(value:String):void {
            _mesAnoTemporario = value;
        }
        public function get mesAnoTemporario():String {
            return _mesAnoTemporario;
        }

        public function set qtdPermanente(value:Number):void {
            _qtdPermanente = value;
        }
        public function get qtdPermanente():Number {
            return _qtdPermanente;
        }

        public function set qtdTemporario(value:Number):void {
            _qtdTemporario = value;
        }
        public function get qtdTemporario():Number {
            return _qtdTemporario;
        }
		
		public function get tipoBeneficiarioSicor():TipoBeneficiarioSicorVO {
			return _tipoBeneficiarioSicor;
		}
		
		public function set tipoBeneficiarioSicor(valor:TipoBeneficiarioSicorVO):void {
			this._tipoBeneficiarioSicor = valor;
		}
		
		public function get idUsuarioEnvio():String
		{
			return _idUsuarioEnvio;
		}
		
		public function set idUsuarioEnvio(value:String):void
		{
			_idUsuarioEnvio = value;
		}

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _categoria = input.readObject() as CategoriaProdutorVO;
            _codigoInscricao = input.readObject() as String;
			_dataHoraInicio = input.readObject() as IDateTime;
			_idUsuarioEnvio  = input.readObject() as String;
            _mesAnoPermanente = input.readObject() as String;
            _mesAnoTemporario = input.readObject() as String;
            _qtdPermanente = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _qtdTemporario = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_tipoBeneficiarioSicor = input.readObject() as TipoBeneficiarioSicorVO;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_categoria);
            output.writeObject(_codigoInscricao);
			output.writeObject(_dataHoraInicio);  
			output.writeObject(_idUsuarioEnvio);
           	output.writeObject(_mesAnoPermanente);
            output.writeObject(_mesAnoTemporario);
            output.writeObject(_qtdPermanente);
            output.writeObject(_qtdTemporario);
			output.writeObject(_tipoBeneficiarioSicor);
        }
    }
}