/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Dec 02 14:36:44 BRST 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (ProdutividadeBaseVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.IDateTime;
    import br.com.sicoob.capes.comum.vo.entidades.EntidadeCadastroBaseVO;
    import br.com.sicoob.capes.comum.vo.entidades.PessoaCompartilhamentoVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class ProdutividadeBaseVOBase extends EntidadeCadastroBaseVO {

        private var _anoFimSafra:Number;
        private var _anoInicioSafra:Number;
		private var _dataHoraInicio:IDateTime;
        private var _descricao:String;
        private var _empreendimento:EmpreendimentoVO;
		private var _idBemAntigo:Number;
		private var _idBemImovel:Number;
        private var _percentualRebate:Number;
        private var _pessoaCompartilhamento:PessoaCompartilhamentoVO;
        private var _producao:Number;
        private var _quantidadeOuArea:Number;
        private var _situacao:Number;
        private var _valorPrecoMedio:Number;
        private var _valorRendaBruta:Number;
		
		public function set dataHoraInicio(value:IDateTime):void {
			_dataHoraInicio = value;
		}
		public function get dataHoraInicio():IDateTime {
			return _dataHoraInicio;
		}

        public function set anoFimSafra(value:Number):void {
            _anoFimSafra = value;
        }
        public function get anoFimSafra():Number {
            return _anoFimSafra;
        }

        public function set anoInicioSafra(value:Number):void {
            _anoInicioSafra = value;
        }
        public function get anoInicioSafra():Number {
            return _anoInicioSafra;
        }

        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set empreendimento(value:EmpreendimentoVO):void {
            _empreendimento = value;
        }
        public function get empreendimento():EmpreendimentoVO {
            return _empreendimento;
        }
		
		public function set idBemAntigo(value:Number):void {
			_idBemAntigo = value;
		}
		public function get idBemAntigo():Number {
			return _idBemAntigo;
		}
		
		public function set idBemImovel(value:Number):void {
			_idBemImovel = value;
		}
		public function get idBemImovel():Number {
			return _idBemImovel;
		}

        public function set percentualRebate(value:Number):void {
            _percentualRebate = value;
        }
        public function get percentualRebate():Number {
            return _percentualRebate;
        }

        public function set pessoaCompartilhamento(value:PessoaCompartilhamentoVO):void {
            _pessoaCompartilhamento = value;
        }
        public function get pessoaCompartilhamento():PessoaCompartilhamentoVO {
            return _pessoaCompartilhamento;
        }

        public function set producao(value:Number):void {
            _producao = value;
        }
        public function get producao():Number {
            return _producao;
        }

        public function set quantidadeOuArea(value:Number):void {
            _quantidadeOuArea = value;
        }
        public function get quantidadeOuArea():Number {
            return _quantidadeOuArea;
        }

        public function set situacao(value:Number):void {
            _situacao = value;
        }
        public function get situacao():Number {
            return _situacao;
        }

        public function set valorPrecoMedio(value:Number):void {
            _valorPrecoMedio = value;
        }
        public function get valorPrecoMedio():Number {
            return _valorPrecoMedio;
        }

        public function set valorRendaBruta(value:Number):void {
            _valorRendaBruta = value;
        }
        public function get valorRendaBruta():Number {
            return _valorRendaBruta;
        }
		
        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _anoFimSafra = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _anoInicioSafra = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_dataHoraInicio = input.readObject() as IDateTime;
            _descricao = input.readObject() as String;
            _empreendimento = input.readObject() as EmpreendimentoVO;
			_idBemAntigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_idBemImovel = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _percentualRebate = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _pessoaCompartilhamento = input.readObject() as PessoaCompartilhamentoVO;
            _producao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _quantidadeOuArea = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _situacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _valorPrecoMedio = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _valorRendaBruta = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_anoFimSafra);
            output.writeObject(_anoInicioSafra);
			output.writeObject(_dataHoraInicio);        	
            output.writeObject(_descricao);
            output.writeObject(_empreendimento);
			output.writeObject(_idBemAntigo);
			output.writeObject(_idBemImovel);
            output.writeObject(_percentualRebate);
            output.writeObject(_pessoaCompartilhamento);
            output.writeObject(_producao);
            output.writeObject(_quantidadeOuArea);
            output.writeObject(_situacao);
            output.writeObject(_valorPrecoMedio);
            output.writeObject(_valorRendaBruta);
        }
    }
}