/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Mon Feb 07 10:55:11 GMT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (ReferenciaBaseVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.IDateTime;
    import br.com.sicoob.capes.comum.vo.entidades.EntidadeCadastroBaseVO;
    import br.com.sicoob.capes.comum.vo.entidades.PessoaCompartilhamentoVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class ReferenciaBaseVOBase extends EntidadeCadastroBaseVO {

		private var _dataHoraInicio:IDateTime;
        private var _ddd:Number;
        private var _observacao:String;
        private var _pessoa:PessoaCompartilhamentoVO;
        private var _pessoaReferencia:PessoaCompartilhamentoVO;
        private var _telefone:String;
        private var _tipoReferencia:TipoReferenciaVO;
		
		public function set dataHoraInicio(value:IDateTime):void {
			_dataHoraInicio = value;
		}
		public function get dataHoraInicio():IDateTime {
			return _dataHoraInicio;
		}

        public function set ddd(value:Number):void {
            _ddd = value;
        }
        public function get ddd():Number {
            return _ddd;
        }

        public function set observacao(value:String):void {
            _observacao = value;
        }
        public function get observacao():String {
            return _observacao;
        }

        public function set pessoa(value:PessoaCompartilhamentoVO):void {
            _pessoa = value;
        }
        public function get pessoa():PessoaCompartilhamentoVO {
            return _pessoa;
        }

        public function set pessoaReferencia(value:PessoaCompartilhamentoVO):void {
            _pessoaReferencia = value;
        }
        public function get pessoaReferencia():PessoaCompartilhamentoVO {
            return _pessoaReferencia;
        }

        public function set telefone(value:String):void {
            _telefone = value;
        }
        public function get telefone():String {
            return _telefone;
        }

        public function set tipoReferencia(value:TipoReferenciaVO):void {
            _tipoReferencia = value;
        }
        public function get tipoReferencia():TipoReferenciaVO {
            return _tipoReferencia;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
			_dataHoraInicio = input.readObject() as IDateTime;
            _ddd =  function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());// input.readObject() as Number;
            _observacao = input.readObject() as String;
            _pessoa = input.readObject() as PessoaCompartilhamentoVO;
            _pessoaReferencia = input.readObject() as PessoaCompartilhamentoVO;
            _telefone = input.readObject() as String;
            _tipoReferencia = input.readObject() as TipoReferenciaVO;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
			output.writeObject(_dataHoraInicio);        	
            output.writeObject(_ddd);
            output.writeObject(_observacao);
            output.writeObject(_pessoa);
            output.writeObject(_pessoaReferencia);
            output.writeObject(_telefone);
            output.writeObject(_tipoReferencia);
        }
    }
}