/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Thu Oct 20 16:49:00 BRST 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RegistroRelacionamentoVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class RegistroRelacionamentoVOBase extends RelacionamentoPessoaVO {

        private var _dadosRegistro:DadosRegistroRelacionamentoVO;

        public function set dadosRegistro(value:DadosRegistroRelacionamentoVO):void {
            _dadosRegistro = value;
        }
        public function get dadosRegistro():DadosRegistroRelacionamentoVO {
            return _dadosRegistro;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
//            if (meta::isInitialized()) {
                _dadosRegistro = input.readObject() as DadosRegistroRelacionamentoVO;
//            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
//            if (meta::isInitialized()) {
            	output.writeObject(_dadosRegistro);
//            }
        }
    }
}