/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Thu Oct 20 16:49:43 BRST 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RelacionamentoPessoaBaseVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.IDateTime;
    import br.com.sicoob.capes.comum.vo.entidades.EntidadeCadastroBaseVO;
	import br.com.sicoob.capes.comum.vo.entidades.PessoaCompartilhamentoVO;
    import br.com.sicoob.capes.comum.vo.entidades.PessoaVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class RelacionamentoPessoaBaseVOBase extends EntidadeCadastroBaseVO {

        private var _dataFimMandato:IDateTime;
		private var _dataInicioMandato:IDateTime;
		private var _dataHoraInicio:IDateTime;
        private var _dataInicioRelacionamento:IDateTime;
        private var _idInstituicao:Number;
        private var _percentualCapitalEmpresa:Number;
        private var _pessoa:PessoaVO;
		private var _pessoaCompartilhamento:PessoaCompartilhamentoVO;
        private var _pessoaRelacionada:PessoaVO;
        private var _tipoRelacionamento:TipoRelacionamentoPessoaVO;
		
		public function set dataHoraInicio(value:IDateTime):void {
			_dataHoraInicio = value;
		}
		public function get dataHoraInicio():IDateTime {
			return _dataHoraInicio;
		}
		
		public function set dataInicioMandato(value:IDateTime):void {
			_dataInicioMandato = value;
		}
		public function get dataInicioMandato():IDateTime {
			return _dataInicioMandato;
		}

        public function set dataFimMandato(value:IDateTime):void {
            _dataFimMandato = value;
        }
        public function get dataFimMandato():IDateTime {
            return _dataFimMandato;
        }

        public function set dataInicioRelacionamento(value:IDateTime):void {
            _dataInicioRelacionamento = value;
        }
        public function get dataInicioRelacionamento():IDateTime {
            return _dataInicioRelacionamento;
        }

        public function set idInstituicao(value:Number):void {
            _idInstituicao = value;
        }
        public function get idInstituicao():Number {
            return _idInstituicao;
        }

        public function set percentualCapitalEmpresa(value:Number):void {
            _percentualCapitalEmpresa = value;
        }
        public function get percentualCapitalEmpresa():Number {
            return _percentualCapitalEmpresa;
        }
		
        public function set pessoa(value:PessoaVO):void {
            _pessoa = value;
        }
        public function get pessoa():PessoaVO {
            return _pessoa;
        }
		
		public function set pessoaCompartilhamento(value:PessoaCompartilhamentoVO):void {
			_pessoaCompartilhamento = value;
		}
		public function get pessoaCompartilhamento():PessoaCompartilhamentoVO {
			return _pessoaCompartilhamento;
		}

        public function set pessoaRelacionada(value:PessoaVO):void {
            _pessoaRelacionada = value;
        }
        public function get pessoaRelacionada():PessoaVO {
            return _pessoaRelacionada;
        }

        public function set tipoRelacionamento(value:TipoRelacionamentoPessoaVO):void {
            _tipoRelacionamento = value;
        }
        public function get tipoRelacionamento():TipoRelacionamentoPessoaVO {
            return _tipoRelacionamento;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
        	_dataFimMandato = input.readObject() as IDateTime;
			_dataHoraInicio = input.readObject() as IDateTime;
			_dataInicioMandato = input.readObject() as IDateTime;
        	_dataInicioRelacionamento = input.readObject() as IDateTime;
            _idInstituicao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _percentualCapitalEmpresa = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
			_pessoa = input.readObject() as PessoaVO;
			_pessoaCompartilhamento = input.readObject() as PessoaCompartilhamentoVO;
            _pessoaRelacionada = input.readObject() as PessoaVO;
            _tipoRelacionamento = input.readObject() as TipoRelacionamentoPessoaVO;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
        	output.writeObject(_dataFimMandato);
			output.writeObject(_dataHoraInicio);        	
			output.writeObject(_dataInicioMandato);
        	output.writeObject(_dataInicioRelacionamento);
            output.writeObject(_idInstituicao);
            output.writeObject(_percentualCapitalEmpresa);
            output.writeObject(_pessoa);
			output.writeObject(_pessoaCompartilhamento);
            output.writeObject(_pessoaRelacionada);
            output.writeObject(_tipoRelacionamento);
        }
    }
}