/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Thu Oct 20 16:48:59 BRST 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RelacionamentoPessoaVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import br.com.sicoob.capes.comum.enums.SituacaoRegistroEnum;
    import br.com.sicoob.capes.comum.enums.TipoAutorizacaoEnum;
    import br.com.sicoob.capes.comum.vo.ReplicavelVO;
    import br.com.sicoob.capes.comum.vo.VigenteVO;
    import br.com.sicoob.capes.comum.vo.entidades.interfaces.Aprovavel;
    import br.com.sicoob.capes.comum.vo.entidades.interfaces.Comprovavel;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ListCollectionView;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class RelacionamentoPessoaVOBase extends RelacionamentoPessoaBaseVO implements VigenteVO, ReplicavelVO, Comprovavel {

        private var __laziness:String = null;

		private var _codigoSituacaoAprovacao:Number;
		private var _documentosComprobatorios:ListCollectionView;
        private var _gravarHistorico:Booleano = new Booleano(true);
		private var _idInstituicaoAtualizacao:Number;
		private var _idRegistroControlado:String;
        private var _idRelacionamento:Number;
		private var _idUsuarioEnvio:String;
        private var _poderes:ListCollectionView;
		private var _produtoBancoob: Booleano = new Booleano(false);
		private var _relacionamentoReverso:RelacionamentoPessoaVO;
		private var _situacaoAprovacao:SituacaoRegistroEnum;
		private var _verificarAutorizacao:Booleano = new Booleano(true);

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is RelacionamentoPessoaVO) || (property as RelacionamentoPessoaVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }
		
		public function set codigoSituacaoAprovacao(value:Number):void{
			_codigoSituacaoAprovacao = value;
		}
		
		public function get codigoSituacaoAprovacao():Number {
			return _codigoSituacaoAprovacao;
		}
		
		public function set situacaoAprovacao(valor:SituacaoRegistroEnum):void{
			_situacaoAprovacao = valor;
		}
		
		public function get situacaoAprovacao():SituacaoRegistroEnum {
			if(_situacaoAprovacao == null){
				_situacaoAprovacao = SituacaoRegistroEnum.valueOff(_codigoSituacaoAprovacao);
			}
			return _situacaoAprovacao;
		}
		
		public function set documentosComprobatorios(value:ListCollectionView):void {
			_documentosComprobatorios = value;
		}
		public function get documentosComprobatorios():ListCollectionView {
			return _documentosComprobatorios;
		}
		
		public function set idInstituicaoAtualizacao(value:Number):void {
			_idInstituicaoAtualizacao = value;
		}
		public function get idInstituicaoAtualizacao():Number {
			return _idInstituicaoAtualizacao;
		}
		
		public function get verificarAutorizacao():Booleano {
			return _verificarAutorizacao;
		}
		public function set verificarAutorizacao(value:Booleano):void {
			_verificarAutorizacao = value;
		}

        public function set gravarHistorico(value:Booleano):void {
            _gravarHistorico = value;
        }
        public function get gravarHistorico():Booleano {
            return _gravarHistorico;
        }

        public function set idRegistroControlado(value:String):void {
            _idRegistroControlado = value;
        }
        public function get idRegistroControlado():String {
            return _idRegistroControlado;
        }

        public function set idRelacionamento(value:Number):void {
            _idRelacionamento = value;
        }
        public function get idRelacionamento():Number {
            return _idRelacionamento;
        }

        public function set poderes(value:ListCollectionView):void {
            _poderes = value;
        }
        public function get poderes():ListCollectionView {
            return _poderes;
        }
		
		public function set relacionamentoReverso(value:RelacionamentoPessoaVO):void {
			_relacionamentoReverso = value;
		}
		public function get relacionamentoReverso():RelacionamentoPessoaVO {
			return _relacionamentoReverso;
		}
		
		public function set produtoBancoob(value:Booleano):void {
			_produtoBancoob = value;
		}
		public function get produtoBancoob():Booleano {
			return _produtoBancoob;
		}
		
		public function get idUsuarioEnvio():String
		{
			return _idUsuarioEnvio;
		}
		
		public function set idUsuarioEnvio(value:String):void
		{
			_idUsuarioEnvio = value; 	
		}
		
        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
				_codigoSituacaoAprovacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_documentosComprobatorios = input.readObject() as ListCollectionView;
            	_gravarHistorico = SerializacaoObjetos.lerBooleano(input);
				_idInstituicaoAtualizacao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_idRegistroControlado = input.readObject() as String;
                _idRelacionamento = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_idUsuarioEnvio  = input.readObject() as String;
				_poderes = input.readObject() as ListCollectionView; 
				_produtoBancoob = SerializacaoObjetos.lerBooleano(input);
				_relacionamentoReverso = input.readObject() as RelacionamentoPessoaVO;
				_situacaoAprovacao = input.readObject() as SituacaoRegistroEnum;
				_verificarAutorizacao = SerializacaoObjetos.lerBooleano(input);
            }
            else {
                _idRelacionamento = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
				output.writeObject(_codigoSituacaoAprovacao);
				output.writeObject(_documentosComprobatorios);
	        	SerializacaoObjetos.escreverBooleano(_gravarHistorico, output);
				output.writeObject(isNaN(_idInstituicaoAtualizacao) ? null : _idInstituicaoAtualizacao);
				output.writeObject(_idRegistroControlado);
	            output.writeObject(_idRelacionamento);
				output.writeObject(_idUsuarioEnvio);
	            output.writeObject(_poderes);
				SerializacaoObjetos.escreverBooleano(_produtoBancoob, output);
				output.writeObject(_relacionamentoReverso);
	            output.writeObject(_situacaoAprovacao);
				SerializacaoObjetos.escreverBooleano(_verificarAutorizacao, output);
            }
            else {
                output.writeObject(_idRelacionamento);
            }
        }
		
		public function get id():Number {
			return idRelacionamento;
		}
		
		public function get tipoAutorizacao():TipoAutorizacaoEnum {
			return TipoAutorizacaoEnum.RELACIONAMENTO;
		}
    }
}