/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package br.com.sicoob.capes.comum.vo.entidades {

	import flash.net.registerClassAlias;

	registerClassAlias("br.com.sicoob.capes.negocio.entidades.RelacionamentoPessoaBase",
			RelacionamentoPessoaBaseVO);
    public class RelacionamentoPessoaBaseVO extends RelacionamentoPessoaBaseVOBase {
    	
    	public function get nomePessoa() : String {
			var retorno:String = "";
			
			if(pessoaCompartilhamento != null) {
				retorno = pessoaCompartilhamento.nomePessoa;
			} else if(pessoa != null) {
				if(pessoa.pessoaCompartilhamento != null) {
					retorno = pessoa.pessoaCompartilhamento.nomePessoa;
				}
			}
			return retorno;
    	}
    	
    	public function get nomePessoaRelacionada() : String {
			var retorno:String = "";
			if(pessoaRelacionada != null) {
				if(pessoaRelacionada.pessoaCompartilhamento != null) {
					retorno = pessoaRelacionada.pessoaCompartilhamento.nomePessoa;
				}
			}
			return retorno;
    	}
		
    }
}