/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Mon Feb 07 10:23:01 GMT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (ResponsavelCadastroBaseVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.IDateTime;
    import br.com.sicoob.capes.comum.vo.entidades.EntidadeCadastroBaseVO;
    import br.com.sicoob.capes.comum.vo.entidades.InstituicaoVO;
    import br.com.sicoob.capes.comum.vo.entidades.PessoaCompartilhamentoVO;
    import br.com.sicoob.capes.comum.vo.entidades.PessoaVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class ResponsavelCadastroBaseVOBase extends EntidadeCadastroBaseVO {

        private var __laziness:String = null;

		private var _dataHoraInicio:IDateTime;
        private var _idInstituicao:Number;
        private var _idPessoaCompartilhamento:Number;
        private var _pessoa:PessoaCompartilhamentoVO;
		
		public function set dataHoraInicio(value:IDateTime):void {
			_dataHoraInicio = value;
		}
		public function get dataHoraInicio():IDateTime {
			return _dataHoraInicio;
		}

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is ResponsavelCadastroBaseVO) || (property as ResponsavelCadastroBaseVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set idPessoaCompartilhamento(value:Number):void {
            _idPessoaCompartilhamento = value;
        }
        public function get idPessoaCompartilhamento():Number {
            return _idPessoaCompartilhamento;
        }

        public function set instituicao(value:Number):void {
            _idInstituicao = value;
        }
        public function get instituicao():Number {
            return _idInstituicao;
        }

        public function set pessoa(value:PessoaCompartilhamentoVO):void {
            _pessoa = value;
        }
        public function get pessoa():PessoaCompartilhamentoVO {
            return _pessoa;
        }

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
				_dataHoraInicio = input.readObject() as IDateTime;
                _idInstituicao = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _idPessoaCompartilhamento = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _pessoa = input.readObject() as PessoaCompartilhamentoVO;
            }
            else {
                _idPessoaCompartilhamento = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
				output.writeObject(_dataHoraInicio);        	
	            output.writeObject(_idInstituicao);
	            output.writeObject(_idPessoaCompartilhamento);
	            output.writeObject(_pessoa);
            }
            else {
                output.writeObject(_idPessoaCompartilhamento);
            }
        }
    }
}