/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Thu May 19 14:46:17 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TelefoneBaseVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.IDateTime;
    import br.com.sicoob.capes.comum.vo.entidades.EntidadeCadastroBaseVO;
    import br.com.sicoob.capes.comum.vo.entidades.PessoaCompartilhamentoVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class TelefoneBaseVOBase extends EntidadeCadastroBaseVO {

		private var _dataHoraInicio:IDateTime;
        private var _ddd:String;
		private var _observacao:String;
		private var _pessoaCompartilhamento:PessoaCompartilhamentoVO;
        private var _ramal:String;
        private var _telefone:String;
        private var _tipoTelefone:TipoTelefoneVO;		
		
		public function set dataHoraInicio(value:IDateTime):void {
			_dataHoraInicio = value;
		}
		public function get dataHoraInicio():IDateTime {
			return _dataHoraInicio;
		}

		public function get descricaoTipoTelefone(): String {
			var valor:String = "";
			if(_tipoTelefone != null) {
				valor = _tipoTelefone.descricao;
			}
			return valor;
		}
		
        public function set ddd(value:String):void {
            _ddd = value;
        }
        public function get ddd():String {
            return _ddd;
        }
		
		public function set observacao(value:String):void {
			_observacao = value;
		}
		public function get observacao():String {
			return _observacao;
		}

        public function set pessoaCompartilhamento(value:PessoaCompartilhamentoVO):void {
            _pessoaCompartilhamento = value;
        }
        public function get pessoaCompartilhamento():PessoaCompartilhamentoVO {
            return _pessoaCompartilhamento;
        }

        public function set ramal(value:String):void {
            _ramal = value;
        }
        public function get ramal():String {
            return _ramal;
        }

        public function set telefone(value:String):void {
            _telefone = value;
        }
        public function get telefone():String {
            return _telefone;
        }

        public function set tipoTelefone(value:TipoTelefoneVO):void {
            _tipoTelefone = value;
        }
        public function get tipoTelefone():TipoTelefoneVO {
            return _tipoTelefone;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
			_dataHoraInicio = input.readObject() as IDateTime;
            _ddd = input.readObject() as String;
			_observacao = input.readObject() as String;
            _pessoaCompartilhamento = input.readObject() as PessoaCompartilhamentoVO;
            _ramal = input.readObject() as String;
            _telefone = input.readObject() as String;
            _tipoTelefone = input.readObject() as TipoTelefoneVO;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
			output.writeObject(_dataHoraInicio);        	
            output.writeObject(_ddd);
			output.writeObject(_observacao);
            output.writeObject(_pessoaCompartilhamento);
            output.writeObject(_ramal);
            output.writeObject(_telefone);
            output.writeObject(_tipoTelefone);
        }
    }
}