/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Aug 05 16:45:14 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TelefoneVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import br.com.sicoob.capes.comum.enums.SituacaoRegistroEnum;
    import br.com.sicoob.capes.comum.enums.TipoAutorizacaoEnum;
    import br.com.sicoob.capes.comum.vo.entidades.interfaces.Aprovavel;
    import br.com.sicoob.capes.comum.vo.ReplicavelVO;
    import br.com.sicoob.capes.comum.vo.VigenteVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class TelefoneVOBase extends TelefoneBaseVO implements ReplicavelVO, VigenteVO {

        private var __laziness:String = null;

        private var _gravarHistorico:Booleano = new Booleano(true);
        private var _idTelefonePessoa:Number;
		private var _idUsuarioEnvio: String;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is TelefoneVO) || (property as TelefoneVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }
		
		
		public function set idUsuarioEnvio(value:String):void{
			_idUsuarioEnvio = value;
		}
		
		public function get idUsuarioEnvio():String {
			return _idUsuarioEnvio;
		}
		
        public function set gravarHistorico(value:Booleano):void {
            _gravarHistorico = value;
        }
        public function get gravarHistorico():Booleano {
            return _gravarHistorico;
        }
		
        public function set idTelefonePessoa(value:Number):void {
            _idTelefonePessoa = value;
        }
        public function get idTelefonePessoa():Number {
            return _idTelefonePessoa;
        }
        
        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
            	_gravarHistorico = SerializacaoObjetos.lerBooleano(input);
                _idTelefonePessoa = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_idUsuarioEnvio = input.readObject() as String;
            }
            else {
                _idTelefonePessoa = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
	        	SerializacaoObjetos.escreverBooleano(_gravarHistorico, output);
	            output.writeObject(isNaN(_idTelefonePessoa) ? null : _idTelefonePessoa);
				output.writeObject(_idUsuarioEnvio);
            }
            else {
                output.writeObject(isNaN(_idTelefonePessoa) ? null : _idTelefonePessoa);
            }
        }
		
		public function get id():Number {
			return idTelefonePessoa;
		}
		
		public function get tipoAutorizacao():TipoAutorizacaoEnum {
			return TipoAutorizacaoEnum.TELEFONE;
		}
    }
}