/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Mon Jan 17 12:52:21 GMT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TipoBaixaVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class TipoBaixaVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

        private var _descTipoBaixa:String;
        private var _idTipoBaixa:Number;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is TipoBaixaVO) || (property as TipoBaixaVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set descTipoBaixa(value:String):void {
            _descTipoBaixa = value;
        }
        public function get descTipoBaixa():String {
            return _descTipoBaixa;
        }

        public function set idTipoBaixa(value:Number):void {
            _idTipoBaixa = value;
        }
        public function get idTipoBaixa():Number {
            return _idTipoBaixa;
        }

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
                _descTipoBaixa = input.readObject() as String;
                _idTipoBaixa = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
            else {
                _idTipoBaixa = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
            output.writeObject(_descTipoBaixa);
            output.writeObject(_idTipoBaixa);
            }
            else {
                output.writeObject(_idTipoBaixa);
            }
        }
    }
}