/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Tue Oct 04 15:23:51 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TipoPoderRelacionamentoVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ListCollectionView;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class TipoPoderRelacionamentoVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

        private var _codigo:Number;
        private var _descricao:String;
		
		private var _relacionamentoPessoa:ListCollectionView;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is TipoPoderRelacionamentoVO) || (property as TipoPoderRelacionamentoVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set codigo(value:Number):void {
            _codigo = value;
        }
        public function get codigo():Number {
            return _codigo;
        }

        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }
		
		public function set relacionamentoPessoa(value:ListCollectionView):void {
			_relacionamentoPessoa = value;
		}
		public function get relacionamentoPessoa():ListCollectionView {
			return _relacionamentoPessoa;
		}

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _descricao = input.readObject() as String;
				_relacionamentoPessoa = input.readObject() as ListCollectionView; 
            }
            else {
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
            output.writeObject(_codigo);
            output.writeObject(_descricao);
			output.writeObject(_relacionamentoPessoa);
            }
            else {
                output.writeObject(_codigo);
            }
        }
    }
}