/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Mon Jan 17 12:52:21 GMT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TipoCapturaVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class TipoMensagemVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

		private var _codTipoMensagem:Number;
        private var _descTipoMensagem:String;
        

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is TipoMensagemVO) || (property as TipoMensagemVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

		public function set codTipoMensagem(value:Number):void {
			_codTipoMensagem = value;
		}
		public function get codTipoMensagem():Number {
			return _codTipoMensagem;
		}
		
        public function set descTipoMensagem(value:String):void {
			_descTipoMensagem = value;
        }
        public function get descTipoMensagem():String {
            return _descTipoMensagem;
        }


        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
				_codTipoMensagem = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_descTipoMensagem = input.readObject() as String;
                
            }
            else {
				_codTipoMensagem = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
			output.writeObject(_codTipoMensagem);
            output.writeObject(_descTipoMensagem);
            }
            else {
                output.writeObject(_codTipoMensagem);
            }
        }
    }
}