/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Jul 13 08:29:34 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TipoCertidaoVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.SerializacaoObjetos;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class TipoCertidaoVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

        private var _codigo:Number;
        private var _dataCancelamento:Date;
        private var _finalidade:String;
        private var _nome:String;
        private var _orgaoEmissor:OrgaoEmissorCertidaoVO;
        private var _prazoValidade:Number;
        private var _sigla:String;
        private var _subTipo:SubTipoCertidaoVO;
        private var _tipoAbrangencia:TipoAbrangenciaCertidaoVO;
        private var _tipoObjeto:TipoObjetoCertidaoVO;
        private var _tipoPrazo:TipoPrazoCertidaoVO;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is TipoCertidaoVO) || (property as TipoCertidaoVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set codigo(value:Number):void {
            _codigo = value;
        }
        public function get codigo():Number {
            return _codigo;
        }

        public function set dataCancelamento(value:Date):void {
            _dataCancelamento = value;
        }
        public function get dataCancelamento():Date {
            return _dataCancelamento;
        }

        public function set finalidade(value:String):void {
            _finalidade = value;
        }
        public function get finalidade():String {
            return _finalidade;
        }

        public function set nome(value:String):void {
            _nome = value;
        }
        public function get nome():String {
            return _nome;
        }

        public function set orgaoEmissor(value:OrgaoEmissorCertidaoVO):void {
            _orgaoEmissor = value;
        }
        public function get orgaoEmissor():OrgaoEmissorCertidaoVO {
            return _orgaoEmissor;
        }

        public function set prazoValidade(value:Number):void {
            _prazoValidade = value;
        }
        public function get prazoValidade():Number {
            return _prazoValidade;
        }

        public function set sigla(value:String):void {
            _sigla = value;
        }
        public function get sigla():String {
            return _sigla;
        }

        public function set subTipo(value:SubTipoCertidaoVO):void {
            _subTipo = value;
        }
        public function get subTipo():SubTipoCertidaoVO {
            return _subTipo;
        }

        public function set tipoAbrangencia(value:TipoAbrangenciaCertidaoVO):void {
            _tipoAbrangencia = value;
        }
        public function get tipoAbrangencia():TipoAbrangenciaCertidaoVO {
            return _tipoAbrangencia;
        }

        public function set tipoObjeto(value:TipoObjetoCertidaoVO):void {
            _tipoObjeto = value;
        }
        public function get tipoObjeto():TipoObjetoCertidaoVO {
            return _tipoObjeto;
        }

        public function set tipoPrazo(value:TipoPrazoCertidaoVO):void {
            _tipoPrazo = value;
        }
        public function get tipoPrazo():TipoPrazoCertidaoVO {
            return _tipoPrazo;
        }

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            	_dataCancelamento = SerializacaoObjetos.lerDate(input);
                _finalidade = input.readObject() as String;
                _nome = input.readObject() as String;
                _orgaoEmissor = input.readObject() as OrgaoEmissorCertidaoVO;
                _prazoValidade = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _sigla = input.readObject() as String;
                _subTipo = input.readObject() as SubTipoCertidaoVO;
                _tipoAbrangencia = input.readObject() as TipoAbrangenciaCertidaoVO;
                _tipoObjeto = input.readObject() as TipoObjetoCertidaoVO;
                _tipoPrazo = input.readObject() as TipoPrazoCertidaoVO;
            }
            else {
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
            output.writeObject(_codigo);
        	SerializacaoObjetos.escreverDate(_dataCancelamento, output);
            output.writeObject(_finalidade);
            output.writeObject(_nome);
            output.writeObject(_orgaoEmissor);
            output.writeObject(_prazoValidade);
            output.writeObject(_sigla);
            output.writeObject(_subTipo);
            output.writeObject(_tipoAbrangencia);
            output.writeObject(_tipoObjeto);
            output.writeObject(_tipoPrazo);
            }
            else {
                output.writeObject(_codigo);
            }
        }
    }
}