/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Aug 26 10:52:30 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TipoEmpresaVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class TipoEmpresaVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

		private var _ativo:Booleano;
        private var _codigo:Number;
        private var _descricao:String;
		private var _isSimplesNacional:Booleano;
		private var _possuiAtivoSuperior:Booleano;
		private var _valorLimiteInferior:Number;
		private var _valorLimiteSuperior:Number;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is TipoEmpresaVO) || (property as TipoEmpresaVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

		
		public function set ativo(value:Booleano):void {
			_ativo = value;
		}
		public function get ativo():Booleano {
			return _ativo;
		}
		
        public function set codigo(value:Number):void {
            _codigo = value;
        }
        public function get codigo():Number {
            return _codigo;
        }

        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }
		
		public function set isSimplesNacional(value:Booleano):void {
			_isSimplesNacional = value;
		}
		public function get isSimplesNacional():Booleano {
			return _isSimplesNacional;
		}
		
		public function set possuiAtivoSuperior(value:Booleano):void {
			_possuiAtivoSuperior = value;
		}
		public function get possuiAtivoSuperior():Booleano {
			return _possuiAtivoSuperior;
		}
		
		public function get valorLimiteSuperior():Number
		{
			return _valorLimiteSuperior;
		}
		
		public function set valorLimiteSuperior(value:Number):void
		{
			_valorLimiteSuperior = value;
		}
		
		public function get valorLimiteInferior():Number
		{
			return _valorLimiteInferior;
		}
		
		public function set valorLimiteInferior(value:Number):void
		{
			_valorLimiteInferior = value;
		}

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
				_ativo = SerializacaoObjetos.lerBooleano(input);
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _descricao = input.readObject() as String;
				_isSimplesNacional = SerializacaoObjetos.lerBooleano(input);
				_possuiAtivoSuperior = SerializacaoObjetos.lerBooleano(input);
				_valorLimiteInferior = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_valorLimiteSuperior = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
            else {
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
				SerializacaoObjetos.escreverBooleano(_ativo, output);
	            output.writeObject(_codigo);
	            output.writeObject(_descricao);
				SerializacaoObjetos.escreverBooleano(_isSimplesNacional, output);
				SerializacaoObjetos.escreverBooleano(_possuiAtivoSuperior, output);
				output.writeObject(_valorLimiteInferior);
				output.writeObject(_valorLimiteSuperior);
            }
            else {
                output.writeObject(_codigo);
            }
        }
    }
}