/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Thu May 19 14:46:16 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TipoLogradouroVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.negocio.entidades.BancoobEmbeddableObject;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class TipoLogradouroVOBase extends BancoobEmbeddableObject {

        private var _idTipoLogradouro:Number;
        private var _nome:String;

        public function set idTipoLogradouro(value:Number):void {
            _idTipoLogradouro = value;
        }
        public function get idTipoLogradouro():Number {
            return _idTipoLogradouro;
        }

        public function set nome(value:String):void {
            _nome = value;
        }
        public function get nome():String {
            return _nome;
        }

        override public function readExternal(input:IDataInput):void {
        	super.readExternal(input);
            _idTipoLogradouro = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
	        _nome = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
        	super.writeExternal(output);
            output.writeObject(_idTipoLogradouro);
            output.writeObject(_nome);
        }
    }
}