/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri May 06 12:42:17 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TipoTelefoneVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class TipoTelefoneVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;
		
		private var _ativo:Booleano;
        private var _codigo:Number;
        private var _descricao:String;
		private var _tipoPessoaContato:TipoPessoaContatoVO;
		private var _dddObrigatorio:Booleano = new Booleano(false);
		private var _numMinDigitos:Number;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is TipoTelefoneVO) || (property as TipoTelefoneVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }
		
		public function set ativo(value:Booleano):void {
			_ativo = value;
		}
		public function get ativo():Booleano {
			return _ativo;
		}

        public function set codigo(value:Number):void {
            _codigo = value;
        }
        public function get codigo():Number {
            return _codigo;
        }

        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }
		
		public function set dddObrigatorio(value:Booleano):void {
			_dddObrigatorio = value;
		}
		
		public function get dddObrigatorio():Booleano {
			return _dddObrigatorio;
		}
		
		public function set numMinDigitos(value:Number):void {
			_numMinDigitos = value;
		}
		public function get numMinDigitos():Number {
			return _numMinDigitos;
		}

		public function set tipoPessoaContato(value:TipoPessoaContatoVO):void {
			_tipoPessoaContato = value;
		}
		public function get tipoPessoaContato():TipoPessoaContatoVO {
			return _tipoPessoaContato;
		}
		
        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
				_ativo = SerializacaoObjetos.lerBooleano(input);
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_dddObrigatorio = SerializacaoObjetos.lerBooleano(input);
                _descricao = input.readObject() as String;
				_numMinDigitos = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
				_tipoPessoaContato = input.readObject() as TipoPessoaContatoVO;
            }
            else {
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
				SerializacaoObjetos.escreverBooleano(_ativo, output);
            	output.writeObject(_codigo);
				SerializacaoObjetos.escreverBooleano(_dddObrigatorio, output);
            	output.writeObject(_descricao);
				output.writeObject(_numMinDigitos);
				output.writeObject(_tipoPessoaContato);
            }
            else {
                output.writeObject(_codigo);
            }
        }
    }
}