/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Tue Oct 04 15:23:49 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TipoRelacionamentoPessoaVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ListCollectionView;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class TipoRelacionamentoPessoaVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

		private var _ativo:Booleano;
        private var _codigo:Number;
        private var _compoeAssinatura:Booleano = new Booleano();
        private var _descricao:String;
        private var _habilitaCapitalSocial:Booleano;
        private var _habilitaDadosRegistro:Booleano;
        private var _habilitaEnvioCCS:Booleano;
        private var _habilitaPoderes:Booleano;
		private var _habilitaProdutosBancoob:Booleano;
		private var _habilitaVerificacaoPendencia:Booleano;
		private var _permiteCompartilhamento:Booleano = new Booleano(true);
        private var _permiteDuplicidade:Booleano = new Booleano(true);
        private var _relacionamentoReverso:TipoRelacionamentoPessoaVO;
        private var _tiposPessoaRelacionada:ListCollectionView;
        private var _tiposPessoaRelacionamento:ListCollectionView;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is TipoRelacionamentoPessoaVO) || (property as TipoRelacionamentoPessoaVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

		public function set ativo(value:Booleano):void {
			_ativo = value;
		}
		public function get ativo():Booleano {
			return _ativo;
		}
		
        public function set codigo(value:Number):void {
            _codigo = value;
        }
        public function get codigo():Number {
            return _codigo;
        }

        public function set compoeAssinatura(value:Booleano):void {
            _compoeAssinatura = value;
        }
        public function get compoeAssinatura():Booleano {
            return _compoeAssinatura;
        }

        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set habilitaCapitalSocial(value:Booleano):void {
            _habilitaCapitalSocial = value;
        }
        public function get habilitaCapitalSocial():Booleano {
            return _habilitaCapitalSocial;
        }

        public function set habilitaDadosRegistro(value:Booleano):void {
            _habilitaDadosRegistro = value;
        }
        public function get habilitaDadosRegistro():Booleano {
            return _habilitaDadosRegistro;
        }

        public function set habilitaEnvioCCS(value:Booleano):void {
            _habilitaEnvioCCS = value;
        }
        public function get habilitaEnvioCCS():Booleano {
            return _habilitaEnvioCCS;
        }

        public function set habilitaPoderes(value:Booleano):void {
            _habilitaPoderes = value;
        }
        public function get habilitaPoderes():Booleano {
            return _habilitaPoderes;
        }
		
		public function set habilitaProdutosBancoob(value:Booleano):void {
			_habilitaProdutosBancoob = value;
		}
		public function get habilitaProdutosBancoob():Booleano {
			return _habilitaProdutosBancoob;
		}
		
		public function set habilitaVerificacaoPendencia(value:Booleano):void {
			_habilitaVerificacaoPendencia = value;
		}
		public function get habilitaVerificacaoPendencia():Booleano {
			return _habilitaVerificacaoPendencia;
		}
		
		public function set permiteCompartilhamento(value:Booleano):void {
			_permiteCompartilhamento = value;
		}
		public function get permiteCompartilhamento():Booleano {
			return _permiteCompartilhamento;
		}
        
        public function set permiteDuplicidade(value:Booleano):void {
        	_permiteDuplicidade = value;
        }
        public function get permiteDuplicidade():Booleano {
        	return _permiteDuplicidade;
        }

        public function set relacionamentoReverso(value:TipoRelacionamentoPessoaVO):void {
            _relacionamentoReverso = value;
        }
        public function get relacionamentoReverso():TipoRelacionamentoPessoaVO {
            return _relacionamentoReverso;
        }

        public function set tiposPessoaRelacionada(value:ListCollectionView):void {
            _tiposPessoaRelacionada = value;
        }
        public function get tiposPessoaRelacionada():ListCollectionView {
            return _tiposPessoaRelacionada;
        }

        public function set tiposPessoaRelacionamento(value:ListCollectionView):void {
            _tiposPessoaRelacionamento = value;
        }
        public function get tiposPessoaRelacionamento():ListCollectionView {
            return _tiposPessoaRelacionamento;
        }

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
				_ativo = SerializacaoObjetos.lerBooleano(input);
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            	_compoeAssinatura = SerializacaoObjetos.lerBooleano(input);
                _descricao = input.readObject() as String;
            	_habilitaCapitalSocial = SerializacaoObjetos.lerBooleano(input);
            	_habilitaDadosRegistro = SerializacaoObjetos.lerBooleano(input);
            	_habilitaEnvioCCS = SerializacaoObjetos.lerBooleano(input);
            	_habilitaPoderes = SerializacaoObjetos.lerBooleano(input);
				_habilitaProdutosBancoob = SerializacaoObjetos.lerBooleano(input);
				_habilitaVerificacaoPendencia = SerializacaoObjetos.lerBooleano(input);
				_permiteCompartilhamento = SerializacaoObjetos.lerBooleano(input);
            	_permiteDuplicidade = SerializacaoObjetos.lerBooleano(input);
                _relacionamentoReverso = input.readObject() as TipoRelacionamentoPessoaVO;
                _tiposPessoaRelacionada = input.readObject() as ListCollectionView;
                _tiposPessoaRelacionamento = input.readObject() as ListCollectionView;
            }
            else {
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
				SerializacaoObjetos.escreverBooleano(_ativo, output);
	            output.writeObject(_codigo);
	        	SerializacaoObjetos.escreverBooleano(_compoeAssinatura, output);
	            output.writeObject(_descricao);
	        	SerializacaoObjetos.escreverBooleano(_habilitaCapitalSocial, output);
	        	SerializacaoObjetos.escreverBooleano(_habilitaDadosRegistro, output);
	        	SerializacaoObjetos.escreverBooleano(_habilitaEnvioCCS, output);
	        	SerializacaoObjetos.escreverBooleano(_habilitaPoderes, output);
				SerializacaoObjetos.escreverBooleano(_habilitaProdutosBancoob, output);
				SerializacaoObjetos.escreverBooleano(_habilitaVerificacaoPendencia, output);
				SerializacaoObjetos.escreverBooleano(_permiteCompartilhamento, output);
	        	SerializacaoObjetos.escreverBooleano(_permiteDuplicidade, output);
	            output.writeObject(_relacionamentoReverso);
	            output.writeObject(_tiposPessoaRelacionada);
	            output.writeObject(_tiposPessoaRelacionamento);
            }
            else {
                output.writeObject(_codigo);
            }
        }
    }
}