/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Tue Jan 25 13:54:43 GMT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TransicaoPessoaVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class TransicaoPessoaVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

        private var _dataHoraIntegracao:Date;
        private var _idPessoaLegado:Number;
        private var _idTransicaoPessoa:Number;
        private var _instituicao:InstituicaoVO;
        private var _nomePessoaLegado:String;
        private var _pessoa:PessoaVO;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is TransicaoPessoaVO) || (property as TransicaoPessoaVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

		public function get numeroInstituicao(): String {
			var valor:String = "";
			if(_instituicao != null) {
				valor = instituicao.numero;
			}
			return valor;
		}        

        public function set dataHoraIntegracao(value:Date):void {
            _dataHoraIntegracao = value;
        }
        public function get dataHoraIntegracao():Date {
            return _dataHoraIntegracao;
        }

        public function set idPessoaLegado(value:Number):void {
            _idPessoaLegado = value;
        }
        public function get idPessoaLegado():Number {
            return _idPessoaLegado;
        }

        public function set idTransicaoPessoa(value:Number):void {
            _idTransicaoPessoa = value;
        }
        public function get idTransicaoPessoa():Number {
            return _idTransicaoPessoa;
        }

        public function set instituicao(value:InstituicaoVO):void {
            _instituicao = value;
        }
        public function get instituicao():InstituicaoVO {
            return _instituicao;
        }

        public function set nomePessoaLegado(value:String):void {
            _nomePessoaLegado = value;
        }
        public function get nomePessoaLegado():String {
            return _nomePessoaLegado;
        }

        public function set pessoa(value:PessoaVO):void {
            _pessoa = value;
        }
        public function get pessoa():PessoaVO {
            return _pessoa;
        }

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
            	_dataHoraIntegracao = SerializacaoObjetos.lerDate(input);
                _idPessoaLegado = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _idTransicaoPessoa = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _instituicao = input.readObject() as InstituicaoVO;
                _nomePessoaLegado = input.readObject() as String;
                _pessoa = input.readObject() as PessoaVO;
            }
            else {
                _idTransicaoPessoa = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
        	SerializacaoObjetos.escreverDate(_dataHoraIntegracao, output);
            output.writeObject(_idPessoaLegado);
            output.writeObject(_idTransicaoPessoa);
            output.writeObject(_instituicao);
            output.writeObject(_nomePessoaLegado);
            output.writeObject(_pessoa);
            }
            else {
                output.writeObject(_idTransicaoPessoa);
            }
        }
    }
}