/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package br.com.sicoob.capes.comum.vo.entidades.bemantigo {
	import flash.net.registerClassAlias;
	import flash.utils.IDataInput;
	import flash.utils.IDataOutput;

    public class BemImovelVO extends BemImovelVOBase {
		
		override public function readExternal(input:IDataInput):void {
			super.readExternal(input);
		}
		
		override public function writeExternal(output:IDataOutput):void {
			super.writeExternal(output);
		}
    }
}