/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Apr 27 11:08:21 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BemOnusBaseVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades.bemantigo {

    import br.com.bancoob.tipos.IDateTime;
    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class BemOnusBaseVOBase extends CAPESEntidadeVO {

        private var __laziness:String = null;

        private var _bem:BemVO;
        private var _dataHoraInicio:IDateTime;
        private var _dataPrevistaLiberacao:IDateTime;
        private var _descricao:String;
        private var _nomeInstituicaoCredora:String;
        private var _numeroGrau:Number;
        private var _valor:Number;
		
        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is BemOnusBaseVO) || (property as BemOnusBaseVO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set bem(value:BemVO):void {
            _bem = value;
        }
        public function get bem():BemVO {
            return _bem;
        }

        public function set dataHoraInicio(value:IDateTime):void {
            _dataHoraInicio = value;
        }
        public function get dataHoraInicio():IDateTime {
            return _dataHoraInicio;
        }

        public function set dataPrevistaLiberacao(value:IDateTime):void {
            _dataPrevistaLiberacao = value;
        }
        public function get dataPrevistaLiberacao():IDateTime {
            return _dataPrevistaLiberacao;
        }

        public function set descricao(value:String):void {
            _descricao = value;
        }
        public function get descricao():String {
            return _descricao;
        }

        public function set nomeInstituicaoCredora(value:String):void {
            _nomeInstituicaoCredora = value;
        }
        public function get nomeInstituicaoCredora():String {
            return _nomeInstituicaoCredora;
        }

        public function set numeroGrau(value:Number):void {
            _numeroGrau = value;
        }
        public function get numeroGrau():Number {
            return _numeroGrau;
        }

        public function set valor(value:Number):void {
            _valor = value;
        }
        public function get valor():Number {
            return _valor;
        }

        override public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                super.readExternal(input);
                _bem = input.readObject() as BemVO;
            	_dataHoraInicio = input.readObject() as IDateTime;
            	_dataPrevistaLiberacao = input.readObject() as IDateTime;
                _descricao = input.readObject() as String;
                _nomeInstituicaoCredora = input.readObject() as String;
                _numeroGrau = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _valor = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }

        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                super.writeExternal(output);
	            output.writeObject(_bem);
	        	output.writeObject(_dataHoraInicio);
	        	output.writeObject(_dataPrevistaLiberacao);
	            output.writeObject(_descricao);
	            output.writeObject(_nomeInstituicaoCredora);
	            output.writeObject(_numeroGrau);
	            output.writeObject(_valor);
            }
        }
    }
}