/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Apr 27 11:08:21 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BemOnusVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades.bemantigo {

    import br.com.bancoob.tipos.Booleano;
    import br.com.bancoob.tipos.SerializacaoObjetos;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class BemOnusVOBase extends BemOnusBaseVO {

        private var _gravarHistorico:Booleano;
        private var _idBemOnus:Number;
        
        public function set gravarHistorico(value:Booleano):void {
            _gravarHistorico = value;
        }
        public function get gravarHistorico():Booleano {
            return _gravarHistorico;
        }


        public function set idBemOnus(value:Number):void {
            _idBemOnus = value;
        }
        public function get idBemOnus():Number {
            return _idBemOnus;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
            	_gravarHistorico = SerializacaoObjetos.lerBooleano(input);
            	_idBemOnus = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            } else {
            	_idBemOnus = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
        		SerializacaoObjetos.escreverBooleano(_gravarHistorico, output);
            	output.writeObject(_idBemOnus);
            }else {
            	output.writeObject(_idBemOnus);            	
            }
        }
    }
}