/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Apr 27 11:08:21 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BemPosseBaseVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades.bemantigo {

    import br.com.bancoob.tipos.IDateTime;
    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class BemPosseBaseVOBase extends CAPESEntidadeVO {

        private var _area:Number;
        private var _bem:BemVO;
        private var _dataHoraInicio:IDateTime;
        private var _tipoPosseBem:TipoPosseBemVO;

        public function set area(value:Number):void {
            _area = value;
        }
        public function get area():Number {
            return _area;
        }

        public function set bem(value:BemVO):void {
            _bem = value;
        }
        public function get bem():BemVO {
            return _bem;
        }

        public function set dataHoraInicio(value:IDateTime):void {
            _dataHoraInicio = value;
        }
        public function get dataHoraInicio():IDateTime {
            return _dataHoraInicio;
        }

        public function set tipoPosseBem(value:TipoPosseBemVO):void {
            _tipoPosseBem = value;
        }
        public function get tipoPosseBem():TipoPosseBemVO {
            return _tipoPosseBem;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _area = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _bem = input.readObject() as BemVO;
        	_dataHoraInicio = input.readObject() as IDateTime;
            _tipoPosseBem = input.readObject() as TipoPosseBemVO;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_area);
            output.writeObject(_bem);
            output.writeObject(_dataHoraInicio);         
            output.writeObject(_tipoPosseBem);
        }
    }
}