/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Apr 27 11:08:21 BRT 2011.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BemRegistroBaseVO.as).
 */

package br.com.sicoob.capes.comum.vo.entidades.bemantigo {

    import br.com.bancoob.tipos.IDateTime;
    import br.com.sicoob.capes.comum.vo.entidades.CAPESEntidadeVO;
    
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class BemRegistroBaseVOBase extends CAPESEntidadeVO {

        private var _areaMatricula:Number;
        private var _bem:BemVO;
        private var _dataHoraInicio:IDateTime;
        private var _dataUltimaMatricula:IDateTime;
        private var _folha:String;
        private var _incra:String;
        private var _ipr:String;
        private var _livro:String;
        private var _matriculaRegistro:String;
        private var _observacaoMatricula:String;

        public function set areaMatricula(value:Number):void {
            _areaMatricula = value;
        }
        public function get areaMatricula():Number {
            return _areaMatricula;
        }

        public function set bem(value:BemVO):void {
            _bem = value;
        }
        public function get bem():BemVO {
            return _bem;
        }

        public function set dataHoraInicio(value:IDateTime):void {
            _dataHoraInicio = value;
        }
        public function get dataHoraInicio():IDateTime {
            return _dataHoraInicio;
        }

        public function set dataUltimaMatricula(value:IDateTime):void {
            _dataUltimaMatricula = value;
        }
        public function get dataUltimaMatricula():IDateTime {
            return _dataUltimaMatricula;
        }

        public function set folha(value:String):void {
            _folha = value;
        }
        public function get folha():String {
            return _folha;
        }

        public function set incra(value:String):void {
            _incra = value;
        }
        public function get incra():String {
            return _incra;
        }

        public function set ipr(value:String):void {
            _ipr = value;
        }
        public function get ipr():String {
            return _ipr;
        }

        public function set livro(value:String):void {
            _livro = value;
        }
        public function get livro():String {
            return _livro;
        }

        public function set matriculaRegistro(value:String):void {
            _matriculaRegistro = value;
        }
        public function get matriculaRegistro():String {
            return _matriculaRegistro;
        }

        public function set observacaoMatricula(value:String):void {
            _observacaoMatricula = value;
        }
        public function get observacaoMatricula():String {
            return _observacaoMatricula;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);

                _areaMatricula = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _bem = input.readObject() as BemVO;
            	_dataHoraInicio = input.readObject() as IDateTime;
            	_dataUltimaMatricula = input.readObject() as IDateTime;
                _folha = input.readObject() as String;
                _incra = input.readObject() as String;
                _ipr = input.readObject() as String;
                _livro = input.readObject() as String;
                _matriculaRegistro = input.readObject() as String;
                _observacaoMatricula = input.readObject() as String;

        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);

            output.writeObject(_areaMatricula);
            output.writeObject(_bem);
        	output.writeObject(_dataHoraInicio);
        	output.writeObject(_dataUltimaMatricula);
            output.writeObject(_folha);
            output.writeObject(_incra);
            output.writeObject(_ipr);
            output.writeObject(_livro);
            output.writeObject(_matriculaRegistro);
            output.writeObject(_observacaoMatricula);

        }
    }
}