/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package br.com.sicoob.capes.comum.vo.entidades.bemantigo {

	import flash.net.registerClassAlias;

	registerClassAlias("br.com.sicoob.capes.negocio.entidades.bemantigo.SituacaoBem",
			SituacaoBemVO);
    public class SituacaoBemVO extends SituacaoBemVOBase {
		
		private var _selected:Boolean=false;
		
		public function set selected(value:Boolean):void {
			_selected = value;
		}
		public function get selected():Boolean {
			return _selected;
		}
		
    }
}