/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package br.com.sicoob.capes.autorizarAlteracoes.dto {
	import br.com.bancoob.dto.RequisicaoDTO;
	
	import flash.net.registerClassAlias;

	registerClassAlias("br.com.sicoob.capes.cadastro.dto.AutorizarReqDTO",
			AutorizacaoReqDTO);
    public class AutorizacaoReqDTO extends RequisicaoDTO {
		
		private var _dados: Object = new Object();

		public function AutorizacaoReqDTO() {
			super();
		}
		
	    public function set dados(value: Object): void {
	        _dados = value;
	    }

	    public function get dados(): Object {
	        return _dados;
	    }
	}
}